export interface HighLowQuestion {
  id: string
  text: string
  answer: number
  unit: string // e.g. "par", "zł", "km"
  hint?: string // shown after reveal
}

export const HIGHLOW_QUESTIONS: HighLowQuestion[] = [
  // --- Ślub i wesele ---
  {
    id: 'hl1',
    text: 'Ile małżeństw zawarto w Polsce w 2022 roku?',
    answer: 140000,
    unit: 'par',
    hint: 'Dane GUS 2022',
  },
  {
    id: 'hl2',
    text: 'Ile złotych kosztuje przeciętne wesele w Polsce?',
    answer: 50000,
    unit: 'zł',
    hint: 'Łącznie z przyjęciem, sukienką i dekoracjami – dane Ślub.pl 2023',
  },
  {
    id: 'hl3',
    text: 'Ile lat ma przeciętna panna młoda biorąca ślub w Polsce?',
    answer: 29,
    unit: 'lat',
    hint: 'Dane GUS 2022; pan młody: 31 lat',
  },
  {
    id: 'hl4',
    text: 'Ile złotych wydaje się przeciętnie na prezent ślubny w Polsce?',
    answer: 500,
    unit: 'zł',
    hint: 'Najczęściej: gotówka lub voucher do sklepu',
  },
  {
    id: 'hl5',
    text: 'Ile gości zaprasza się na przeciętne polskie wesele?',
    answer: 120,
    unit: 'osób',
    hint: 'Tendencja spadkowa – coraz popularniejsze wesela kameralne (do 30 osób)',
  },
  {
    id: 'hl6',
    text: 'Ile procent małżeństw w Polsce kończy się rozwodem?',
    answer: 33,
    unit: '%',
    hint: 'Co trzecia para; w największych miastach ten odsetek jest wyższy',
  },
  {
    id: 'hl7',
    text: 'Ile złotych kosztuje przeciętna suknia ślubna w Polsce?',
    answer: 3500,
    unit: 'zł',
    hint: 'Projektanci premium: 10 000–50 000 zł; sieciówki: od 600 zł',
  },
  {
    id: 'hl8',
    text: 'Ile procent Polaków bierze ślub kościelny wg GUS 2022?',
    answer: 53,
    unit: '%',
    hint: 'Spadek z ok. 80% w 2005 r.; tendencja malejąca rok do roku',
  },
  {
    id: 'hl9',
    text: 'Ile dni trwało małżeństwo Kim Kardashian z Kris Humphriesem?',
    answer: 72,
    unit: 'dni',
    hint: 'Ślub 20 sierpnia 2011 r.; złożenie wniosku o rozwód 31 października 2011 r.',
  },
  {
    id: 'hl10',
    text: 'Ile godzin trwało najkrótsze małżeństwo gwiazdy — Britney Spears z Jasonem Alexandrem?',
    answer: 55,
    unit: 'godzin',
    hint: 'Ślub w Las Vegas 3 stycznia 2004 r.; unieważniony 2 dni później',
  },
  {
    id: 'hl11',
    text: 'Ile lat trwało najdłuższe małżeństwo w historii (Herbert i Zelmyra Fisher, Guinness)?',
    answer: 86,
    unit: 'lat',
    hint: 'Pobrali się w 1924 r.; Herbert zmarł w 2011 r. w wieku 105 lat',
  },
  {
    id: 'hl12',
    text: 'Ile krajów na świecie uznaje małżeństwa jednopłciowe (stan 2024)?',
    answer: 36,
    unit: 'krajów',
    hint: 'Od Holandii (2001) do kolejnych państw; Polska ich nie uznaje',
  },
  {
    id: 'hl13',
    text: 'Ile złotych kosztuje przeciętna para obrączek ślubnych ze złota w Polsce?',
    answer: 4000,
    unit: 'zł',
    hint: 'Za parę obrączek ze złota 585; platyna i brylanty to wielokrotność tej kwoty',
  },
  {
    id: 'hl14',
    text: 'Ile złotych kosztuje przeciętnie fotograf ślubny w Polsce?',
    answer: 5000,
    unit: 'zł',
    hint: 'Ceny za pełny reportaż; topowi fotografowie: 15 000–30 000 zł',
  },
  {
    id: 'hl15',
    text: 'Ile milionów dolarów kosztowało wesele Vanishy Mittal (córki miliardera) w Paryżu w 2004 r.?',
    answer: 60,
    unit: 'mln USD',
    hint: 'Uważane za jedno z najdroższych wesel w historii; goście z całego świata',
  },

  // --- Ludzkie ciało ---
  {
    id: 'hl16',
    text: 'Ile razy bije serce człowieka w ciągu jednej doby?',
    answer: 100000,
    unit: 'uderzeń',
    hint: '70 uderzeń/min × 60 × 24 ≈ 100 800; serce nigdy się nie zatrzymuje',
  },
  {
    id: 'hl17',
    text: 'Ile km ma sieć naczyń krwionośnych w ludzkim ciele?',
    answer: 100000,
    unit: 'km',
    hint: 'Wystarczyłoby 2,5 razy okrążyć Ziemię (obwód: ~40 000 km)',
  },
  {
    id: 'hl18',
    text: 'Ile metrów ma jelito cienkie człowieka?',
    answer: 6,
    unit: 'metrów',
    hint: 'Zakres: 5–7 m; jelito grube: ok. 1,5 m; cały układ pokarmowy: ~9 m',
  },
  {
    id: 'hl19',
    text: 'Ile kości ma dorosły człowiek?',
    answer: 206,
    unit: 'kości',
    hint: 'Niemowlęta: ok. 270–300 kości – wiele zrasta się z wiekiem',
  },
  {
    id: 'hl20',
    text: 'Ile miliardów neuronów ma ludzki mózg?',
    answer: 86,
    unit: 'miliardów neuronów',
    hint: 'Badanie Suzany Herculano-Houzel (2009); dawne szacunki: 100 mld – lekko przesadzone',
  },
  {
    id: 'hl21',
    text: 'Ile metrów DNA mieści się w jednej komórce ciała?',
    answer: 2,
    unit: 'metry',
    hint: 'DNA nawinięte na histony upakowane w jądrze o średnicy 6 mikrometrów',
  },
  {
    id: 'hl22',
    text: 'Ile procent wody zawiera ciało dorosłego człowieka?',
    answer: 60,
    unit: '%',
    hint: 'Niemowlęta: ~75%; starsze osoby: ~50%; kobiety mają mniej wody niż mężczyźni',
  },
  {
    id: 'hl23',
    text: 'Ile m² wynosi powierzchnia skóry dorosłego człowieka?',
    answer: 2,
    unit: 'm²',
    hint: 'Skóra waży ok. 3–4 kg i jest największym narządem w ciele',
  },
  {
    id: 'hl24',
    text: 'Ile kg waży ludzki mózg?',
    answer: 1.4,
    unit: 'kg',
    hint: 'Ok. 1,4–1,5 kg; pochłania 20% energii organizmu, choć stanowi tylko 2% masy ciała',
  },
  {
    id: 'hl25',
    text: 'Ile m/s przewodzi impuls nerwowy w najszybszych włóknach nerwowych (typ Aα)?',
    answer: 120,
    unit: 'm/s',
    hint: '120 m/s = 432 km/h; włókna bólowe wolne (typ C): ok. 1 m/s – stąd opóźnienie bólu',
  },
  {
    id: 'hl26',
    text: 'Ile procent energii ciała zużywa mózg?',
    answer: 20,
    unit: '%',
    hint: 'Stanowi 2% masy, ale pochłania 20% glukozy i tlenu; szczególnie aktywny podczas snu REM',
  },
  {
    id: 'hl27',
    text: 'Ile mm miesięcznie rośnie paznokieć u ręki?',
    answer: 3,
    unit: 'mm/miesiąc',
    hint: 'Roczny przyrost: ok. 3,6 cm; u nóg ok. 2× wolniej; szybciej latem i u dominującej ręki',
  },
  {
    id: 'hl28',
    text: 'Ile razy na dobę mruga człowiek przeciętnie?',
    answer: 20000,
    unit: 'razy',
    hint: 'Ok. 14–17 mgnięć/minutę × 1440 min; jedno mgnięcie trwa 0,1–0,4 sekundy',
  },
  {
    id: 'hl29',
    text: 'Ile litrów krwi pompuje serce człowieka w ciągu jednej doby?',
    answer: 7200,
    unit: 'litrów',
    hint: '5 l/min × 60 × 24 = 7 200 l; serce przepompowuje całą krew (~5 l) co minutę',
  },
  {
    id: 'hl30',
    text: 'Ile lat żyła najstarsza udokumentowana osoba w historii — Jeanne Calment?',
    answer: 122,
    unit: 'lat',
    hint: 'Jeanne Louise Calment (Francja, 1875–1997); jej rekord nie został do dziś pobity',
  },
  {
    id: 'hl31',
    text: 'Ile stopni Celsjusza wynosi normalna temperatura ciała człowieka?',
    answer: 37,
    unit: '°C',
    hint: 'Norma: 36,1–37,2°C; "gorączka" od 38°C; temperatura rano jest niższa niż wieczorem',
  },
  {
    id: 'hl32',
    text: 'Ile procent masy ciała stanowią mięśnie szkieletowe u mężczyzny?',
    answer: 40,
    unit: '% masy ciała',
    hint: 'Ok. 600–640 mięśni szkieletowych; u kobiet: ~30%; razem to ok. 700 mięśni w całym ciele',
  },
  {
    id: 'hl33',
    text: 'Ile razy na minutę oddycha człowiek w spoczynku?',
    answer: 15,
    unit: 'oddechów/min',
    hint: 'Norma: 12–20/min; podczas wysiłku: do 60; noworodki: 30–60/min',
  },

  // --- Rekordy Guinnessa ---
  {
    id: 'hl34',
    text: 'Ile cm wzrostu miał najwyższy człowiek w historii — Robert Wadlow?',
    answer: 272,
    unit: 'cm',
    hint: 'Robert Wadlow (USA, 1918–1940); cierpiał na gigantyzm przysadkowy; wciąż rósł do śmierci',
  },
  {
    id: 'hl35',
    text: 'Ile godzin trwał najdłuższy pocałunek w historii (Guinness)?',
    answer: 58,
    unit: 'godzin',
    hint: 'Ekkachai i Laksana Tiranarat (Tajlandia, 2013): 58 godz. 35 min 58 sek.',
  },
  {
    id: 'hl36',
    text: 'Ile cm ma najdłuższy język na świecie — Nick Stoeberl (Guinness 2012)?',
    answer: 10,
    unit: 'cm',
    hint: 'Dokładnie 10,1 cm; mierzony od środka zamkniętych ust do czubka języka',
  },
  {
    id: 'hl37',
    text: 'Ile kg ważył najcięższy człowiek w historii — Jon Brower Minnoch?',
    answer: 635,
    unit: 'kg',
    hint: 'Jon Brower Minnoch (USA, 1941–1983); Guinness World Records; cierpiał na masywny obrzęk',
  },
  {
    id: 'hl38',
    text: 'Ile kg ważył najcięższy noworodek, który przeżył (Guinness)?',
    answer: 10,
    unit: 'kg',
    hint: '10,2 kg – urodzony w Aversa (Włochy) 25 września 1955 r.; Guinness World Records',
  },
  {
    id: 'hl39',
    text: 'Ile dzieci urodziła jedna kobieta w historii (żona Fiodora Wasiljewa, Rosja XVIII w.)?',
    answer: 69,
    unit: 'dzieci',
    hint: '27 porodów: 16 par bliźniąt, 7 trojaczków, 4 czworaczki; Guinness World Records',
  },
  {
    id: 'hl40',
    text: 'Ile cm wynosiła łączna długość paznokci rekordzistki Lee Redmond (Guinness)?',
    answer: 865,
    unit: 'cm łącznie',
    hint: 'Lee Redmond (USA) – 8,65 m łącznie; hodowała od 1979 r.; straciła je w wypadku w 2009 r.',
  },
  {
    id: 'hl41',
    text: 'Ile metrów wynosi rekord świata w skoku w dal mężczyzn (Mike Powell, 1991)?',
    answer: 8,
    unit: 'metrów',
    hint: 'Dokładnie 8,95 m (Tokio, 1991); pobił rekord Boba Beamona sprzed 23 lat',
  },
  {
    id: 'hl42',
    text: 'Ile lat miał najstarszy człowiek, który ukończył maraton — Fauja Singh?',
    answer: 100,
    unit: 'lat',
    hint: 'Toronto Waterfront Marathon, 2011 r.; czas: 8:11:06; urodzony w Indiach w 1911 r.',
  },
  {
    id: 'hl43',
    text: 'Ile metrów n.p.m. ma Mount Everest wg pomiaru z 2020 roku?',
    answer: 8849,
    unit: 'm n.p.m.',
    hint: 'Chiński pomiar 2020: 8 848,86 m; poprzednia oficjalna wysokość: 8 848 m',
  },
  {
    id: 'hl44',
    text: 'Ile km/h osiąga gepard — najszybsze zwierzę lądowe?',
    answer: 112,
    unit: 'km/h',
    hint: 'Sprint do 500 m; dla porównania: koń: ~88 km/h, lew: ~80 km/h',
  },
  {
    id: 'hl45',
    text: 'Ile km ma najdłuższa rzeka świata — Nil?',
    answer: 6650,
    unit: 'km',
    hint: 'Nil: 6 650 km (tradycyjny pomiar); Amazonka: 6 400 km; spór o najdłuższą trwa',
  },
  {
    id: 'hl46',
    text: 'Ile mln USD osiągnął obraz Salvator Mundi Leonarda da Vinci na aukcji w 2017 r.?',
    answer: 450,
    unit: 'mln USD',
    hint: 'Christie\'s, Nowy Jork, 15 listopada 2017 r. – najdrożej sprzedane dzieło sztuki w historii',
  },
  {
    id: 'hl47',
    text: 'Ile lat żyją żółwie olbrzymie Seychelles (szacunkowo)?',
    answer: 150,
    unit: 'lat',
    hint: 'Jonathan z Wyspy Świętej Heleny ma ponad 190 lat (ur. ok. 1832); najstarsze żyjące zwierzę lądowe',
  },

  // --- Polska ---
  {
    id: 'hl48',
    text: 'Ile milionów mieszkańców liczy Polska?',
    answer: 37,
    unit: 'mln osób',
    hint: 'GUS 2023: 37,6 mln; spadek przez emigrację i niski przyrost naturalny',
  },
  {
    id: 'hl49',
    text: 'Ile km lądowej granicy ma Polska z sąsiadami łącznie?',
    answer: 3071,
    unit: 'km',
    hint: 'Z Niemcami, Czechami, Słowacją, Ukrainą, Białorusią, Litwą i Rosją (Królewiec); granica morska: ~770 km',
  },
  {
    id: 'hl50',
    text: 'Ile złotych wynosi minimalna pensja w Polsce od 1 stycznia 2024?',
    answer: 4242,
    unit: 'zł brutto',
    hint: 'Od 1 lipca 2024: 4 300 zł; w 2015 r. było to 1 750 zł – niemal 2,5× wzrost przez 9 lat',
  },
  {
    id: 'hl51',
    text: 'Ile złotych wynosi przeciętne wynagrodzenie brutto w Polsce (GUS 2023)?',
    answer: 7540,
    unit: 'zł brutto',
    hint: 'Wzrost z ok. 3 400 zł w 2013 r.; netto (na rękę): ok. 5 400 zł',
  },
  {
    id: 'hl52',
    text: 'Ile km² ma powierzchnia Polski?',
    answer: 312685,
    unit: 'km²',
    hint: '69. miejsce na świecie; podobna wielkością do Niemiec, mniejsza od nich o ok. 44 000 km²',
  },
  {
    id: 'hl53',
    text: 'Ile lat ma Warszawa jako stolica Polski (od przeniesienia dworu przez Zygmunta III Wazę)?',
    answer: 428,
    unit: 'lat',
    hint: 'Zygmunt III Waza przeniósł dwór z Krakowa do Warszawy w 1596 r. (stan na rok 2024)',
  },
  {
    id: 'hl54',
    text: 'Ile procent kobiet w Polsce w grupie 25–34 lata ma wyższe wykształcenie?',
    answer: 50,
    unit: '%',
    hint: 'Polska kobiety: ~50%, mężczyźni: ~37%; jeden z najwyższych odsetków w UE (Eurostat 2022)',
  },
  {
    id: 'hl55',
    text: 'Ile lat wynosi przeciętna długość życia kobiety w Polsce?',
    answer: 81,
    unit: 'lat',
    hint: 'GUS 2022; mężczyźni: 74 lata; luka 7 lat to jedna z większych w UE',
  },
  {
    id: 'hl56',
    text: 'Ile złotych za metr kwadratowy płaci się za mieszkanie w centrum Warszawy (2023)?',
    answer: 18000,
    unit: 'zł/m²',
    hint: 'Dane AMRON-SARFiN Q3 2023; najdroższe oferty w Śródmieściu: ponad 30 000 zł/m²',
  },
  {
    id: 'hl57',
    text: 'Ile procent Polaków posiada własne mieszkanie lub dom?',
    answer: 85,
    unit: '%',
    hint: 'Jeden z najwyższych wskaźników własności w UE; Niemcy: ok. 50%, Szwajcaria: ok. 42%',
  },

  // --- Nauka i biologia ---
  {
    id: 'hl58',
    text: 'Ile procent DNA człowieka jest identyczne z DNA szympansa?',
    answer: 98,
    unit: '%',
    hint: 'Dokładnie 98,7%; różnica 1,3% to miliony lat ewolucji i kilka tysięcy lat kulturowej przepaści',
  },
  {
    id: 'hl59',
    text: 'Ile procent DNA człowieka jest identyczne z DNA banana?',
    answer: 50,
    unit: '%',
    hint: 'Ok. 50% wspólnych genów; odpowiadają za podstawowe funkcje komórkowe zachowane ewolucyjnie',
  },
  {
    id: 'hl60',
    text: 'Ile procent DNA jest identyczne u wszystkich ludzi na Ziemi?',
    answer: 99,
    unit: '%',
    hint: 'Dokładnie 99,9%; różnimy się jedynie 0,1% – ale to i tak miliony wariantów genetycznych',
  },
  {
    id: 'hl61',
    text: 'Ile lat świetlnych dzieli nas od najbliższej gwiazdy — Proxima Centauri?',
    answer: 4,
    unit: 'lata świetlne',
    hint: 'Dokładnie 4,24 roku świetlnego; rakieta New Horizons dotarłaby tam za ok. 70 000 lat',
  },
  {
    id: 'hl62',
    text: 'Ile miliardów lat liczy Ziemia?',
    answer: 4,
    unit: 'miliardy lat',
    hint: 'Dokładnie ok. 4,54 mld lat; Wszechświat ma ok. 13,8 mld lat',
  },
  {
    id: 'hl63',
    text: 'Ile procent powierzchni Ziemi pokrywają oceany?',
    answer: 71,
    unit: '%',
    hint: 'Ocean Spokojny sam zajmuje ponad 30% powierzchni Ziemi; zbadano mniej niż 20% dna oceanów',
  },
  {
    id: 'hl64',
    text: 'Ile milionów gatunków zwierząt szacuje się, że żyje na Ziemi?',
    answer: 8,
    unit: 'mln gatunków',
    hint: 'Badanie Mora et al. 2011: 8,7 mln eukariotów; odkryto i opisano ok. 1,2 mln gatunków',
  },
  {
    id: 'hl65',
    text: 'Ile km od Ziemi jest Księżyc (średnia odległość)?',
    answer: 384000,
    unit: 'km',
    hint: 'Orbita eliptyczna: 356 500 do 406 700 km; Księżyc oddala się od Ziemi o 3,8 cm rocznie',
  },
  {
    id: 'hl66',
    text: 'Ile stopni Celsjusza panuje w centrum Słońca?',
    answer: 15000000,
    unit: '°C',
    hint: '15 milionów °C; powierzchnia Słońca: ok. 5 500°C; korona słoneczna: ponad 1 mln °C',
  },

  // --- Ciekawostki ---
  {
    id: 'hl67',
    text: 'Ile procent czasu swojego życia człowiek spędza na śnie?',
    answer: 33,
    unit: '%',
    hint: '8 godzin/dobę = 33% doby; przez 75 lat życia to ok. 25 lat spędzonych na śnie',
  },
  {
    id: 'hl68',
    text: 'Ile słów wypowiada przeciętna osoba dziennie (niezależnie od płci)?',
    answer: 16000,
    unit: 'słów',
    hint: 'Badanie Pennebakera (2007): ok. 15 669 słów; mit o tym, że kobiety mówią 2× więcej — obalony',
  },
  {
    id: 'hl69',
    text: 'Ile lat zajęło zbudowanie Wielkiej Piramidy Cheopsa?',
    answer: 20,
    unit: 'lat',
    hint: 'Ok. 2560–2540 p.n.e.; pracowało przy niej ok. 20 000–30 000 robotników (nie niewolników)',
  },
  {
    id: 'hl70',
    text: 'Ile godzin dziennie przeciętny człowiek patrzy w ekran telefonu?',
    answer: 4,
    unit: 'godziny',
    hint: 'Raport App Annie 2022; wśród młodych dorosłych (18–25 lat): ponad 6 godzin/dzień',
  },
  {
    id: 'hl71',
    text: 'Ile minut dziennie przeciętna osoba spędza na toalecie?',
    answer: 30,
    unit: 'minut/dzień',
    hint: 'Badanie British Journal of Medical Practice; przez całe życie to ok. 3 lata na sedesie',
  },
  {
    id: 'hl72',
    text: 'Ile snów ma przeciętny człowiek w ciągu jednej nocy?',
    answer: 5,
    unit: 'snów',
    hint: 'Większość zapominamy w 5 minut po przebudzeniu; marzenia senne pojawiają się podczas fazy REM',
  },
  {
    id: 'hl73',
    text: 'Ile procent kobiet w Polsce pracuje zawodowo (wskaźnik aktywności zawodowej, GUS 2022)?',
    answer: 62,
    unit: '%',
    hint: 'Wzrost z 54% w 2005 r.; dla mężczyzn: ~73%; w Szwecji kobiety: ~80%',
  },
  {
    id: 'hl74',
    text: 'Ile lat zajmuje wzrost kawy od zasadzenia do pierwszych owoców?',
    answer: 4,
    unit: 'lat',
    hint: 'Krzewy kawowca żyją do 60 lat; zbieranie owoców (wiśni kawowych) jest w większości ręczne',
  },

  // --- Sport ---
  {
    id: 'hl75',
    text: 'Ile sekund wynosi rekord świata kobiet w biegu na 100 m (Florence Griffith-Joyner, 1988)?',
    answer: 10,
    unit: 'sekund',
    hint: 'Dokładnie 10,49 sek. – ustanowiony 16 lipca 1988 r. na US Olympic Trials; rekord niepobity do dziś',
  },
  {
    id: 'hl76',
    text: 'Ile sekund brakowało rekordziście maratonu mężczyzn — Kelvinowi Kiptumowi (2023) — do przebicia bariery 2 godzin?',
    answer: 35,
    unit: 'sekund',
    hint: 'Kiptum przebiegł maraton w 2:00:35 w Chicago, 8 X 2023; pobił rekord Kipchoge o prawie minutę',
  },
  {
    id: 'hl77',
    text: 'Ile km/h osiągnął najszybszy serwis w historii tenisa (Sam Groth, 2012)?',
    answer: 263,
    unit: 'km/h',
    hint: 'Dokładnie 263,4 km/h; Busan Open Challenger, Korea Płd., 2012; Guinness World Records',
  },
  {
    id: 'hl78',
    text: 'Ile metrów wynosi rekord świata w skoku o tyczce (Armand Duplantis, Paryż 2024)?',
    answer: 6,
    unit: 'metrów',
    hint: 'Dokładnie 6,25 m – ustanowiony na igrzyskach olimpijskich w Paryżu, 5 sierpnia 2024 r.',
  },
  {
    id: 'hl79',
    text: 'Ile bramek strzelił Lionel Messi w roku 2012, bijąc rekord Guinnessa dla goli w roku kalendarzowym?',
    answer: 91,
    unit: 'goli',
    hint: '79 dla Barcelony + 12 dla Argentyny; pobił rekord Gerda Müllera z 1972 roku (85 goli)',
  },
  {
    id: 'hl80',
    text: 'Ile złotych medali olimpijskich zdobył Michael Phelps w swojej karierze?',
    answer: 23,
    unit: 'złotych medali',
    hint: '28 medali łącznie (23 złote, 3 srebrne, 2 brązowe); rekordzista w historii igrzysk olimpijskich',
  },
  {
    id: 'hl81',
    text: 'Ile tytułów Wielkiego Szlema zdobył Novak Djoković (stan: US Open 2023)?',
    answer: 24,
    unit: 'tytułów',
    hint: 'Pobił rekordy Federera i Nadala; triumfował w Australian Open, Roland Garros, Wimbledonie i US Open',
  },
  {
    id: 'hl82',
    text: 'Ile minut trwał najdłuższy mecz tenisowy w historii — Isner kontra Mahut (Wimbledon 2010)?',
    answer: 665,
    unit: 'minut',
    hint: '11 godzin 5 minut rozłożonych na 3 dni; wynik piątego seta: 70:68 dla Isnera',
  },
  {
    id: 'hl83',
    text: 'Ile punktów zdobył Wilt Chamberlain w jednym meczu NBA (rekord wszech czasów, 1962)?',
    answer: 100,
    unit: 'punktów',
    hint: 'Philadelphia Warriors vs New York Knicks, 2 marca 1962; nikt nawet nie zbliżył się do tego rekordu',
  },
  {
    id: 'hl84',
    text: 'Ile bramek strzelił Miroslav Klose we wszystkich edycjach Mistrzostw Świata w piłce nożnej?',
    answer: 16,
    unit: 'goli',
    hint: 'Rekordzista MŚ wszech czasów; grał w 2002, 2006, 2010 i 2014 (finał); wyprzedził Ronaldo z 15',
  },

  // --- Zwierzęta ---
  {
    id: 'hl85',
    text: 'Ile ton może ważyć płetwal błękitny — największe zwierzę na Ziemi?',
    answer: 150,
    unit: 'ton',
    hint: 'Najcięższa udokumentowana samica: ok. 173 ton; to więcej niż 20 słoni afrykańskich razem',
  },
  {
    id: 'hl86',
    text: 'Ile miesięcy trwa ciąża słonia afrykańskiego?',
    answer: 22,
    unit: 'miesięcy',
    hint: 'Najdłuższa ciąża spośród wszystkich ssaków lądowych; noworodek waży ok. 100 kg',
  },
  {
    id: 'hl87',
    text: 'Ile km/h osiąga sokół wędrowny podczas nurkowania z wysokości — najszybszy ptak na Ziemi?',
    answer: 389,
    unit: 'km/h',
    hint: 'Zarejestrowany z użyciem GPS; w poziomym locie: ok. 100–150 km/h; nurkowanie to potężna broń',
  },
  {
    id: 'hl88',
    text: 'Ile uderzeń na minutę osiąga serce kolibra podczas intensywnego lotu?',
    answer: 1200,
    unit: 'uderzeń/min',
    hint: 'W spoczynku: ok. 250 bpm; dla porównania człowiek podczas wysiłku: max ok. 200 bpm',
  },
  {
    id: 'hl89',
    text: 'Ile kg waży jajko strusia — największe jajko spośród współcześnie żyjących ptaków?',
    answer: 1.5,
    unit: 'kg',
    hint: 'Zakres: 1,0–2,0 kg; równowartość ok. 24 jajek kurzych; grubość skorupki: ok. 2 mm',
  },
  {
    id: 'hl90',
    text: 'Ile metrów może mierzyć żyrafa — najwyższe zwierzę lądowe na świecie?',
    answer: 5.5,
    unit: 'metrów',
    hint: 'Samce: 4,8–5,7 m; rekord Guinness: "Forest" – 5,88 m (Kenya, 2019); szyja: ok. 2,4 m',
  },
  {
    id: 'hl91',
    text: 'Ile km musi przelecieć kolonia pszczół, aby zebrać nektar potrzebny do wyprodukowania 1 kg miodu?',
    answer: 90000,
    unit: 'km',
    hint: 'Łącznie ok. 90 000 km i 2 miliony odwiedzonych kwiatów; to ponad 2× okrążenie Ziemi',
  },
  {
    id: 'hl92',
    text: 'Ile razy na minutę bije serce płetwala błękitnego podczas głębokiego nurkowania?',
    answer: 2,
    unit: 'uderzeń/min',
    hint: 'Zbadano biologgerami GPS; na powierzchni: 25–37 bpm; skrajne zwolnienie to adaptacja do nurkowania',
  },
  {
    id: 'hl93',
    text: 'Ile lat liczy Metuzalem — najstarsze żyjące drzewo (sosna długowieczna, USA)?',
    answer: 4856,
    unit: 'lat',
    hint: 'Odkryte w 1957 r. w White Mountains w Kalifornii; lokalizacja utajniona dla ochrony drzewa',
  },
  {
    id: 'hl94',
    text: 'Ile metrów głębokości osiągnął walń dziobaty Cuviera — rekordzista wśród nurkujących ssaków?',
    answer: 2992,
    unit: 'metrów',
    hint: 'Zarejestrowany przez NOAA w 2014 r.; nurkowanie trwało 2 godziny 17 minut',
  },
  {
    id: 'hl95',
    text: 'Ile woltów może wygenerować węgorz elektryczny?',
    answer: 860,
    unit: 'V',
    hint: 'Zarejestrowany w 2019 r. w Amazonii; publikacja w Nature Communications; wystarczy by ogłuszyć konia',
  },
  {
    id: 'hl96',
    text: 'Ile oczu ma pszczoła miodna?',
    answer: 5,
    unit: 'oczu',
    hint: '2 duże oczy złożone + 3 proste oczy (ocelli) na czubku głowy wykrywające natężenie światła',
  },

  // --- Jedzenie i kulinaria ---
  {
    id: 'hl97',
    text: 'Ile jednostek Scoville\'a ma papryczka Carolina Reaper — oficjalnie najostrzejsza na świecie (Guinness)?',
    answer: 2200000,
    unit: 'SHU',
    hint: 'Tabasco: ok. 2 500 SHU; habanero: ok. 350 000 SHU; Carolina Reaper to inny wymiar ostrości',
  },
  {
    id: 'hl98',
    text: 'Ile kalorii ma Big Mac w McDonald\'s?',
    answer: 550,
    unit: 'kcal',
    hint: 'Wartości odżywcze wg McDonald\'s Polska; z frytkami i colą to już ok. 1 200 kcal',
  },
  {
    id: 'hl99',
    text: 'Ile kalorii ma 100 g gorzkiej czekolady (70% kakao)?',
    answer: 600,
    unit: 'kcal',
    hint: 'Mleczna: ok. 535 kcal/100g; biała: ok. 560 kcal/100g; gorzka ma więcej tłuszczu kakao',
  },
  {
    id: 'hl100',
    text: 'Ile mg kofeiny zawiera pojedyncze espresso (30 ml)?',
    answer: 65,
    unit: 'mg',
    hint: 'Zakres: 47–75 mg w zależności od ziarna i parzenia; kawa filtrowana (200 ml): 80–120 mg',
  },
  {
    id: 'hl101',
    text: 'Ile m² miała największa pizza na świecie upieczona jednorazowo (Guinness, Rzym 2012)?',
    answer: 1261,
    unit: 'm²',
    hint: 'Zespół Dovilio Nardi; 13 580 stóp kwadratowych; zajęła całą halę wystawienniczą',
  },
  {
    id: 'hl102',
    text: 'Ile kg ważyła najcięższa dynia na świecie (rekord Guinnessa 2023, Travis Gienger, USA)?',
    answer: 1247,
    unit: 'kg',
    hint: 'Travis Gienger z Minnesoty uprawił dynię 2 749 funtów; Minnesota State Fair, październik 2023',
  },
  {
    id: 'hl103',
    text: 'Ile procent światowej produkcji kawy pochodzi z Brazylii?',
    answer: 37,
    unit: '%',
    hint: 'Brazylia to od 150 lat niekwestionowany lider; nr 2: Wietnam (~16%); nr 3: Kolumbia (~8%)',
  },
  {
    id: 'hl104',
    text: 'Ile stopni Celsjusza wynosi temperatura wrzenia wody na szczycie Mount Everest?',
    answer: 70,
    unit: '°C',
    hint: 'Na poziomie morza: 100°C; na Everest (8 849 m): ok. 69–70°C – jajko ugotowane tam będzie surowe w środku',
  },
  {
    id: 'hl105',
    text: 'Ile gramów cukru zawiera standardowa puszka Coca-Coli (330 ml)?',
    answer: 35,
    unit: 'gramów',
    hint: 'Ok. 10,6 g/100 ml × 330 ml ≈ 35 g; to niemal 7 łyżeczek cukru; WHO zaleca max 25 g/dzień dla kobiet',
  },

  // --- Geografia ---
  {
    id: 'hl106',
    text: 'Ile metrów głębokości ma Rów Mariański — najgłębsze miejsce na Ziemi?',
    answer: 11034,
    unit: 'metrów',
    hint: 'Challenger Deep; odkryty w 1875 r.; ciśnienie na dnie: ponad 1 000 atm',
  },
  {
    id: 'hl107',
    text: 'Ile metrów głębokości ma jezioro Bajkał — najgłębsze jezioro na świecie?',
    answer: 1642,
    unit: 'metrów',
    hint: 'Bajkał zawiera ok. 20% całej słodkiej wody powierzchniowej Ziemi; ma 25 mln lat',
  },
  {
    id: 'hl108',
    text: 'Ile metrów wysokości ma Wodospad Anioła — najwyższy wodospad świata (Wenezuela)?',
    answer: 979,
    unit: 'metrów',
    hint: 'Salto Ángel; 15× wyższy od Niagary; odkryty przez lotnika Jimmy\'ego Angela w 1933 r.',
  },
  {
    id: 'hl109',
    text: 'Ile km mierzy Wielki Mur Chiński wraz ze wszystkimi odgałęzieniami i rowami wg badań z 2012 roku?',
    answer: 21196,
    unit: 'km',
    hint: 'Chińska Akademia Nauk, 2012; budowany przez ok. 2 000 lat; widoczny z samolotu, nie z kosmosu',
  },
  {
    id: 'hl110',
    text: 'Ile milionów km² zajmuje Sahara — największa gorąca pustynia na świecie?',
    answer: 9,
    unit: 'mln km²',
    hint: 'Dokładnie ok. 9,2 mln km²; rozciąga się na 11 krajach; rozmiarami zbliżona do USA',
  },
  {
    id: 'hl111',
    text: 'Ile metrów poniżej poziomu morza leży powierzchnia Morza Martwego?',
    answer: 430,
    unit: 'metrów poniżej morza',
    hint: 'Najniżej położony punkt na lądzie na Ziemi; zasolenie ok. 34% sprawia, że ciało unosi się samo',
  },
  {
    id: 'hl112',
    text: 'Ile metrów n.p.m. ma Kilimandżaro — najwyższy szczyt Afryki?',
    answer: 5895,
    unit: 'm n.p.m.',
    hint: 'Szczyt Uhuru, Tanzania; wulkan uśpiony; ma własny lodowiec, który topnieje z roku na rok',
  },
  {
    id: 'hl113',
    text: 'Ile milionów km² zajmuje Rosja — największy kraj świata?',
    answer: 17,
    unit: 'mln km²',
    hint: 'Dokładnie 17,1 mln km²; to ok. 11% powierzchni wszystkich lądów; rozciąga się na 11 stref czasowych',
  },
  {
    id: 'hl114',
    text: 'Ile km ma Tunel Bazowy Gottardu — najdłuższy tunel kolejowy na świecie (Szwajcaria, 2016)?',
    answer: 57,
    unit: 'km',
    hint: 'Dokładnie 57,1 km; przebija Alpy pod masywem Gottardu; budowany 17 lat; koszt: ok. 12 mld CHF',
  },

  // --- Technologia i kultura ---
  {
    id: 'hl115',
    text: 'Ile godzin materiału wideo jest wgrywanych na YouTube każdej minuty?',
    answer: 500,
    unit: 'godzin/minutę',
    hint: 'Dane YouTube 2022; gdyby oglądać non-stop to obejrzenie jednej minuty uploadów zajęłoby 82 lata',
  },
  {
    id: 'hl116',
    text: 'Ile dolarów kosztował pierwszy iPhone w dniu premiery (2007)?',
    answer: 499,
    unit: 'USD',
    hint: 'Zaprezentowany przez Steve\'a Jobsa 9 stycznia 2007; sprzedany 29 czerwca 2007 r.; 4 GB: $499, 8 GB: $599',
  },
  {
    id: 'hl117',
    text: 'Ile miliardów dolarów zarobił film Avatar Jamesa Camerona łącznie w kinach na całym świecie?',
    answer: 2,
    unit: 'miliardy USD',
    hint: 'Dokładnie ok. 2,92 mld USD (z re-releases); najdroższa produkcja i jeden z dwóch filmów > 2,9 mld USD',
  },
  {
    id: 'hl118',
    text: 'Ile milionów kopii sprzedał album Thriller Michaela Jacksona — najlepiej sprzedająca się płyta w historii?',
    answer: 66,
    unit: 'mln kopii',
    hint: 'Wydany w 1982 r.; szacunki 66–70 mln; zawiera hity: Billie Jean, Beat It, Thriller; 8 nagród Grammy',
  },
  {
    id: 'hl119',
    text: 'Ile milionów kopii sprzedał Minecraft — najlepiej sprzedająca się gra wideo w historii (stan 2021)?',
    answer: 238,
    unit: 'mln kopii',
    hint: 'Dane Microsoft 2021; we wszystkich platformach łącznie; do 2024 r. wynik jeszcze wzrósł',
  },
  {
    id: 'hl120',
    text: 'Ile miliardów wyświetleń zebrał film Baby Shark Dance na YouTube (najpopularniejszy klip ever)?',
    answer: 13,
    unit: 'miliardów wyświetleń',
    hint: 'Kanał Pinkfong; przekroczył 13 mld w 2024 r.; wyprzedził Despacito i Shape of You',
  },
  {
    id: 'hl121',
    text: 'Ile milionów utworów można znaleźć na platformie Spotify (2023)?',
    answer: 100,
    unit: 'mln utworów',
    hint: 'Dane Spotify Q4 2023; dodawanych jest ok. 100 000 nowych piosenek dziennie',
  },
  {
    id: 'hl122',
    text: 'Ile ton ważył ENIAC — pierwszy programowalny komputer elektroniczny (USA, 1945)?',
    answer: 27,
    unit: 'ton',
    hint: 'Zajmował powierzchnię 167 m²; miał 18 000 lamp próżniowych; moc obliczeniowa: 100 operacji/sekundę',
  },
  {
    id: 'hl123',
    text: 'Ile milionów obserwujących miał Cristiano Ronaldo na Instagramie (2024) — najwięcej na świecie?',
    answer: 620,
    unit: 'mln obserwujących',
    hint: 'Pierwsze konto z > 600 mln; wyprzedza samego Instagrama i celebrytki pokroju Seleny Gomez',
  },
  {
    id: 'hl124',
    text: 'Ile milionów płatnych subskrybentów miał Netflix na całym świecie na koniec 2023 roku?',
    answer: 260,
    unit: 'mln subskrybentów',
    hint: 'Dane Netflix Q4 2023: 260,28 mln; wzrost o 29 mln w ciągu roku dzięki walce z dzieleniem kont',
  },

  // --- Historia ---
  {
    id: 'hl125',
    text: 'Ile widzów mogło jednocześnie pomieścić Koloseum w starożytnym Rzymie?',
    answer: 50000,
    unit: 'widzów',
    hint: 'Szacunki: 50 000–80 000; inauguracja w 80 r. n.e.; 100 dni igrzysk — zginęło 9 000 zwierząt',
  },
  {
    id: 'hl126',
    text: 'Ile metrów mierzyła Wieża Eiffla w chwili otwarcia w 1889 roku (bez anten)?',
    answer: 300,
    unit: 'metrów',
    hint: 'Z aktualną anteną: 330 m; przez 41 lat najwyższa budowla świata; zbudowana w 2 lata, 2 miesiące, 5 dni',
  },
  {
    id: 'hl127',
    text: 'Ile metrów długości miał Titanic?',
    answer: 269,
    unit: 'metrów',
    hint: 'Dokładnie 269,1 m; szerokość: 28,2 m; wypornność: 46 328 BRT; zatonął 15 kwietnia 1912 r.',
  },
  {
    id: 'hl128',
    text: 'Ile lat trwała budowa katedry Notre-Dame w Paryżu (1163–1345)?',
    answer: 182,
    unit: 'lat',
    hint: 'Pracowało przy niej kilka pokoleń mistrzów budowlanych; spłonęła w 2019 r., odbudowana do 2024 r.',
  },
  {
    id: 'hl129',
    text: 'Ile cm wzrostu miał Napoleon Bonaparte?',
    answer: 168,
    unit: 'cm',
    hint: 'Był wzrostu przeciętnego jak na epokę (Francuzi: ok. 165 cm); mit o jego niskim wzroście to wynik pomyłki w przeliczeniu cali na cm',
  },
  {
    id: 'hl130',
    text: 'Ile lat trwała II wojna światowa (od inwazji na Polskę do kapitulacji Japonii)?',
    answer: 6,
    unit: 'lat',
    hint: '1 września 1939 (Polska) – 2 września 1945 (Japonia); zginęło ok. 70–85 milionów ludzi',
  },

  // --- Kosmos ---
  {
    id: 'hl131',
    text: 'Ile km/h osiąga Międzynarodowa Stacja Kosmiczna krążąc wokół Ziemi?',
    answer: 27600,
    unit: 'km/h',
    hint: 'Okrąża Ziemię co ok. 90 minut (16 razy na dobę); prędkość niezbędna do utrzymania orbity na wysokości ~408 km',
  },
  {
    id: 'hl132',
    text: 'Ile km nad Ziemią krąży Międzynarodowa Stacja Kosmiczna (ISS)?',
    answer: 408,
    unit: 'km',
    hint: 'Orbita niska (LEO); ISS widać gołym okiem jako jasny punkt przesuwający się przez niebo z prędkością ok. 8 km/s',
  },
  {
    id: 'hl133',
    text: 'Ile dni spędził kosmonauta Waleri Polakow w kosmosie bez przerwy (rekord jednej misji, Mir, 1994–1995)?',
    answer: 437,
    unit: 'dni',
    hint: 'Pobyt od 8 I 1994 do 22 III 1995; głównym celem było zbadanie wpływu długiej mikrograwitacji na zdrowie',
  },
  {
    id: 'hl134',
    text: 'Ile km/h osiągnęła sonda Parker Solar Probe zbliżając się do Słońca (2024) — najszybszy obiekt stworzony przez człowieka?',
    answer: 692000,
    unit: 'km/h',
    hint: 'Dokładnie ~692 000 km/h podczas historycznego przelotu 24 XII 2024 z odległości 6,1 mln km od Słońca',
  },
  {
    id: 'hl135',
    text: 'Ile milionów km dzieli Ziemię od Marsa (średnia odległość)?',
    answer: 225,
    unit: 'mln km',
    hint: 'Zakres: 54 mln km (opozycja) do 401 mln km (koniunkcja); podróż rakietą: ok. 6–9 miesięcy',
  },
  {
    id: 'hl136',
    text: 'Ile potwierdzonych egzoplanet odkryła NASA (stan 2024)?',
    answer: 5600,
    unit: 'egzoplanet',
    hint: 'Baza NASA Exoplanet Archive; większość odkryto metodą tranzytową przez teleskop Kepler i TESS',
  },
  {
    id: 'hl137',
    text: 'Ile milionów km od Ziemi stacjonuje Teleskop Kosmiczny Jamesa Webba (JWST) w punkcie libracyjnym L2?',
    answer: 1.5,
    unit: 'mln km',
    hint: 'Wystrzelony 25 XII 2021; obserwuje w podczerwieni; zdolność rozdzielcza 100× lepsza niż Hubble\'a w tym zakresie',
  },
  {
    id: 'hl138',
    text: 'Ile tysięcy lat świetlnych wynosi średnica naszej galaktyki — Drogi Mlecznej?',
    answer: 100,
    unit: 'tys. lat świetlnych',
    hint: 'Układ Słoneczny leży ok. 26 000 lat świetlnych od centrum; Droga Mleczna ma ok. 200–400 mld gwiazd',
  },
  {
    id: 'hl139',
    text: 'Ile osób w historii stanęło na powierzchni Księżyca?',
    answer: 12,
    unit: 'osób',
    hint: 'Wszyscy byli Amerykanami; 6 misji Apollo (11, 12, 14, 15, 16, 17); ostatni: Gene Cernan i Harrison Schmitt (1972)',
  },
  {
    id: 'hl140',
    text: 'Ile miliardów km od Ziemi jest sonda Voyager 1 (stan 2024) — najdalszy obiekt stworzony przez człowieka?',
    answer: 23,
    unit: 'mld km',
    hint: 'Wystrzelona w 1977 r.; porusza się z prędkością ok. 17 km/s; sygnał radiowy z Voyagera dociera do Ziemi po ok. 22 godzinach',
  },

  // --- Transport i prędkość ---
  {
    id: 'hl141',
    text: 'Ile km/h osiągnął Bugatti Chiron Super Sport 300+ — certyfikowany najszybszy samochód seryjny (2019)?',
    answer: 490,
    unit: 'km/h',
    hint: 'Dokładnie 490,484 km/h; kierowca Andy Wallace; tor Ehra-Lessien w Niemczech; limitowany fabrycznie do 440 km/h',
  },
  {
    id: 'hl142',
    text: 'Ile km/h osiągnął japoński pociąg maglev SCMaglev L0 podczas próby rekordowej (2015)?',
    answer: 603,
    unit: 'km/h',
    hint: 'Unosi się na polu magnetycznym 10 cm nad torem; planowana trasa Tokio–Osaka (286 km) w ok. 40 minut',
  },
  {
    id: 'hl143',
    text: 'Ile km/h wynosiła prędkość przelotowa Concorde — naddźwiękowego samolotu pasażerskiego (1976–2003)?',
    answer: 2179,
    unit: 'km/h',
    hint: 'Mach 2,04; lot Londyn/Paryż–Nowy Jork w 3,5 h zamiast standardowych 7–8 h; wycofany po katastrofie w 2000 r.',
  },
  {
    id: 'hl144',
    text: 'Ile km liczy Kolej Transsyberyjska — najdłuższa linia kolejowa świata?',
    answer: 9289,
    unit: 'km',
    hint: 'Moskwa–Władywostok; przejeżdża przez 8 stref czasowych; podróż trwa ok. 7 dni; budowana 1891–1916',
  },
  {
    id: 'hl145',
    text: 'Ile metrów długości ma Ever Alot — jeden z największych kontenerowców świata (2022)?',
    answer: 400,
    unit: 'metrów',
    hint: 'Dokładnie 399,9 m; przewozi 24 004 kontenery TEU; szerokość: 61,5 m; armator: Evergreen Marine',
  },
  {
    id: 'hl146',
    text: 'Ile godzin trwał pierwszy samotny przelot Charlesa Lindbergha przez Atlantyk (1927)?',
    answer: 33,
    unit: 'godzin',
    hint: 'Dokładnie 33 h 30 min; Nowy Jork → Paryż (5 809 km) w Spirit of St. Louis; bez radia, bez snu, bez spadochronu',
  },
  {
    id: 'hl147',
    text: 'Ile minut minęło od uderzenia Titanica w górę lodową do jego całkowitego zatonięcia?',
    answer: 160,
    unit: 'minut',
    hint: 'Uderzenie: 23:40 14 IV 1912; zatonięcie: 2:20 15 IV 1912 — dokładnie 2 godziny i 40 minut',
  },
  {
    id: 'hl148',
    text: 'Ile km/h osiągnął SR-71 Blackbird — najszybszy odrzutowiec z załogą w historii?',
    answer: 3540,
    unit: 'km/h',
    hint: 'Mach ~3,3; rekord ustanowiony w 1976 r.; skóra samolotu nagrzewała się do 300°C podczas lotu',
  },

  // --- Ekonomia i biznes ---
  {
    id: 'hl149',
    text: 'Ile miliardów dolarów kosztowała budowa Międzynarodowej Stacji Kosmicznej — najdroższego projektu w historii człowieka?',
    answer: 150,
    unit: 'mld USD',
    hint: 'Łącznie z eksploatacją; finansowana przez NASA (~100 mld), Rosję (~12 mld), ESA, JAXA i CSA',
  },
  {
    id: 'hl150',
    text: 'Ile dolarów kosztował 1 Bitcoin w historycznym szczycie cenowym (listopad 2021)?',
    answer: 69000,
    unit: 'USD',
    hint: '69 044 USD (10 listopada 2021); zaledwie rok wcześniej: ok. 10 000 USD; w marcu 2024 przekroczył 73 000 USD',
  },
  {
    id: 'hl151',
    text: 'Ile milionów dolarów zarobiła Taylor Swift na Eras Tour (2023) — pierwsza artystka z przychodem ponad 1 mld USD z jednej trasy?',
    answer: 1040,
    unit: 'mln USD',
    hint: 'Oficjalne dane Pollstar; każdy show: ok. 13 mln USD; trasa objęła 5 kontynentów i 151 koncertów',
  },
  {
    id: 'hl152',
    text: 'Ile bilionów dolarów wynosi łączny PKB świata (IMF, 2023)?',
    answer: 105,
    unit: 'bilionów USD',
    hint: 'USA: ~27 bln, Chiny: ~18 bln, Niemcy: ~4,5 bln, Polska: ~0,75 bln; świat rośnie o ok. 3% rocznie',
  },
  {
    id: 'hl153',
    text: 'Ile miliardów dolarów wynosił szczytowy majątek Elona Muska (2021) — rekord historyczny?',
    answer: 340,
    unit: 'mld USD',
    hint: 'Szczyt: ok. 340 mld USD w XI 2021 r. dzięki akcjom Tesli; po przejęciu Twittera majątek mocno spadł i ponownie urósł',
  },
  {
    id: 'hl154',
    text: 'Ile milionów dolarów kosztowała produkcja Pirates of the Caribbean: Na nieznanych wodach (2011) — najdroższego filmu w historii?',
    answer: 379,
    unit: 'mln USD',
    hint: 'Walt Disney Pictures; Johnny Depp, Penélope Cruz; oficjalny budżet produkcji (bez kosztów marketingu)',
  },

  // --- Klimat i środowisko ---
  {
    id: 'hl155',
    text: 'Ile cząsteczek CO₂ na milion zawiera atmosfera Ziemi (pomiar NOAA, maj 2023) — nowy rekord historyczny?',
    answer: 424,
    unit: 'ppm',
    hint: 'W epoce przedprzemysłowej (ok. 1750): ok. 280 ppm; wzrost o 52% w ciągu 270 lat',
  },
  {
    id: 'hl156',
    text: 'Ile milionów ton plastiku trafia do oceanów każdego roku?',
    answer: 8,
    unit: 'mln ton/rok',
    hint: 'Szacunki Jambeck et al. (Science, 2015); łączna masa plastiku w oceanie to ponad 150 mln ton',
  },
  {
    id: 'hl157',
    text: 'Ile milionów km² zajmuje Wielka Pacyficzna Plama Śmietna — największe skupisko plastiku w oceanie?',
    answer: 1.6,
    unit: 'mln km²',
    hint: 'Odkryta przez Charlesa Moore\'a w 1997 r.; to 3× powierzchnia Francji; gęstość: ok. 60 000 cząstek/km²',
  },
  {
    id: 'hl158',
    text: 'Ile procent słodkiej wody Ziemi jest zamrożone w lodowcach i czapach polarnych?',
    answer: 70,
    unit: '%',
    hint: 'Antarktyka: ok. 60%; Grenlandia: ok. 10%; reszta to lodowce górskie i wieczna zmarzlina',
  },
  {
    id: 'hl159',
    text: 'Ile stopni Celsjusza wynosi najwyższa temperatura odnotowana na Ziemi (Dolina Śmierci, USA, 1913)?',
    answer: 56.7,
    unit: '°C',
    hint: 'Furnace Creek, 10 VII 1913 r.; w 2021 r. zmierzono 54,4°C w Death Valley — prawie powtórzono rekord',
  },
  {
    id: 'hl160',
    text: 'Ile stopni Celsjusza wynosi najniższa temperatura odnotowana na Ziemi (stacja Wostok, Antarktyda, 1983)?',
    answer: -89.2,
    unit: '°C',
    hint: '21 VII 1983 r.; Antarktyda to najzimniejszy, najwyższy, najsuchszy i najwietrzniejszy kontynent',
  },

  // --- Muzyka ---
  {
    id: 'hl161',
    text: 'Ile tygodni utrzymywał się na szczycie listy Billboard Hot 100 utwór Old Town Road Lil Nas X (2019) — absolutny rekord?',
    answer: 19,
    unit: 'tygodni',
    hint: 'Pobił rekord sprzed 25 lat (Mariah Carey & Boyz II Men — One Sweet Day: 16 tygodni)',
  },
  {
    id: 'hl162',
    text: 'Ile nagród Grammy zdobyła Beyoncé łącznie (stan 2024) — więcej niż jakikolwiek artysta w historii?',
    answer: 32,
    unit: 'nagród Grammy',
    hint: 'Pobiła rekord Georga Soltiego (31); 88 nominacji; nagrody obejmują pop, R&B, country i muzykę klasyczną',
  },
  {
    id: 'hl163',
    text: 'Ile lat ma trwać wykonanie utworu As Slow As Possible Johna Cage\'a w kościele w Halberstadt w Niemczech?',
    answer: 639,
    unit: 'lat',
    hint: 'Zaczęło się 5 IX 2001; zakończy 4 IX 2640; zmiana dźwięku raz na kilka lat; specjalnie zbudowane organy',
  },
  {
    id: 'hl164',
    text: 'Ile milionów płyt sprzedali The Beatles — szacowana łączna sprzedaż na świecie?',
    answer: 600,
    unit: 'mln kopii',
    hint: 'RIAA certyfikowała 183 mln w USA; globalnie szacuje się 600–800 mln; nadal sprzedają się lepiej niż większość aktywnych artystów',
  },
  {
    id: 'hl165',
    text: 'Ile miliardów odtworzeń zebrał Blinding Lights The Weeknd na Spotify — najczęściej słuchana piosenka w historii platformy (2024)?',
    answer: 4,
    unit: 'mld odtworzeń',
    hint: 'Ponad 4,3 mld streamów; przez wiele lat rekordzistą był Shape of You Eda Sheerana; Blinding Lights wyprzedził w 2023',
  },
  {
    id: 'hl166',
    text: 'Ile bramek strzelił Just Fontaine (Francja) na jednym Mistrzostwie Świata (1958) — rekord niepobity od 66 lat?',
    answer: 13,
    unit: 'goli',
    hint: 'MŚ 1958 w Szwecji; 6 meczów, 13 goli; Francja zajęła 3. miejsce; Fontaine strzelał w każdym meczu',
  },

  // --- Architektura i budowle ---
  {
    id: 'hl167',
    text: 'Ile metrów mierzy Burdż Chalifa w Dubaju — najwyższy budynek świata?',
    answer: 828,
    unit: 'metrów',
    hint: 'Otwarty 4 I 2010; 163 piętra; panoramiczny widok z tarasu: do 95 km; zbudowany w 6 lat',
  },
  {
    id: 'hl168',
    text: 'Ile km liczy Wiadukt Danyang-Kunshan w Chinach — najdłuższy most na świecie (2011)?',
    answer: 165,
    unit: 'km',
    hint: 'Linia kolejowa dużych prędkości Szanghaj–Nanjing; 10 000 robotników przez 4 lata; koszt: ok. 8,5 mld USD',
  },
  {
    id: 'hl169',
    text: 'Ile okien ma Empire State Building w Nowym Jorku?',
    answer: 6514,
    unit: 'okien',
    hint: 'Zbudowany w zaledwie 410 dni (1930–1931); 102 piętra; przez 40 lat był najwyższym budynkiem świata',
  },
  {
    id: 'hl170',
    text: 'Ile lat trwała budowa Koloseum w Rzymie (70–80 n.e.)?',
    answer: 10,
    unit: 'lat',
    hint: 'Cesarz Wespazjan zlecił, syn Tytus otworzył; użyto ok. 100 000 m³ trawertynu i 300 ton żelaza',
  },
  {
    id: 'hl171',
    text: 'Ile km liczy Kanał Panamski łączący Ocean Atlantycki z Pacyfikiem?',
    answer: 77,
    unit: 'km',
    hint: 'Budowany przez USA 1904–1914; dziś przepływa przez niego ok. 14 000 statków rocznie; rozbudowany w 2016 r.',
  },
  {
    id: 'hl172',
    text: 'Ile lat trwała budowa Opery w Sydney — jednego z najbardziej rozpoznawalnych budynków świata?',
    answer: 14,
    unit: 'lat',
    hint: 'Projekt: Jørn Utzon (1957); budowa 1959–1973; pierwotny kosztorys: 7 mln AUD; finalny koszt: 102 mln AUD',
  },

  // --- Medycyna i zdrowie ---
  {
    id: 'hl173',
    text: 'Ile lat trwał Human Genome Project — sekwencjonowanie całego ludzkiego genomu (1990–2003)?',
    answer: 13,
    unit: 'lat',
    hint: 'Koszt: 2,7 mld USD; 20 instytutów z 6 krajów; dziś sekwencjonowanie zajmuje 1 dzień i kosztuje ok. 1 000 USD',
  },
  {
    id: 'hl174',
    text: 'Ile dni żyje czerwona krwinka w ludzkim organizmie?',
    answer: 120,
    unit: 'dni',
    hint: 'Produkowana w szpiku kostnym; rozkładana w śledzionie i wątrobie; nie ma jądra, dzięki czemu więcej miejsca na hemoglobinę',
  },
  {
    id: 'hl175',
    text: 'Ile dni pościł Angus Barbieri pod nadzorem lekarzy (1965–1966) — rekord Guinnessa w terapeutycznym poście?',
    answer: 382,
    unit: 'dni',
    hint: 'Ważył 207 kg na starcie; po poście: 82 kg (chudł 382 dni!); pił tylko herbatę, kawę i wodę z elektrolitami',
  },
  {
    id: 'hl176',
    text: 'Ile miliardów dawek szczepionek przeciw COVID-19 podano na całym świecie (stan 2024)?',
    answer: 13,
    unit: 'mld dawek',
    hint: 'Dane Our World in Data; pierwsze szczepienie: 8 XII 2020 w Wielkiej Brytanii (Margaret Keenan, 90 lat)',
  },
  {
    id: 'hl177',
    text: 'Ile chromosomów ma prawidłowa komórka ludzka?',
    answer: 46,
    unit: 'chromosomów',
    hint: '23 pary: 22 pary autosomów + 1 para płciowa (XX lub XY); trisomia 21 (3 chr. nr 21) = zespół Downa',
  },
  {
    id: 'hl178',
    text: 'Ile miliardów razy bije serce człowieka przez całe 75-letnie życie (szacunkowo)?',
    answer: 3,
    unit: 'mld uderzeń',
    hint: '70 uderzeń/min × 525 600 min/rok × 75 lat ≈ 2,76 mld; serce nigdy nie odpoczywa przez całe życie',
  },

  // --- Polska historia i kultura ---
  {
    id: 'hl179',
    text: 'Ile krajów odwiedził Jan Paweł II podczas swojego pontyfikatu?',
    answer: 104,
    unit: 'krajów',
    hint: '129 zagranicznych podróży; pokonał łącznie ponad 1,7 mln km — ponad 4× odległość Ziemia–Księżyc',
  },
  {
    id: 'hl180',
    text: 'Ile dni trwało Powstanie Warszawskie w 1944 roku?',
    answer: 63,
    unit: 'dni',
    hint: '1 VIII – 2 X 1944; zginęło ok. 200 000 cywilów i 16 000 żołnierzy AK; po upadku Niemcy zburzyli 85% miasta',
  },
  {
    id: 'hl181',
    text: 'Ile Nagród Nobla zdobyła Maria Skłodowska-Curie?',
    answer: 2,
    unit: 'Nagrody Nobla',
    hint: 'Fizyka (1903, razem z Piotrem) i Chemia (1911); jedyna osoba z Noblem w dwóch różnych dziedzinach nauk ścisłych',
  },
  {
    id: 'hl182',
    text: 'Ile milionów członków liczyła Solidarność w szczytowym momencie (1981)?',
    answer: 10,
    unit: 'mln członków',
    hint: 'Największy niezależny związek zawodowy w historii bloku wschodniego; założona w sierpniu 1980 w Gdańsku',
  },
  {
    id: 'hl183',
    text: 'Ile nokturnów skomponował Fryderyk Chopin?',
    answer: 21,
    unit: 'nokturnów',
    hint: 'Opusy 9, 15, 27, 32, 37, 48, 55, 62 oraz dwa bez opusu; formę nokturnu przejął od Johna Fielda',
  },
  {
    id: 'hl184',
    text: 'Ile lat trwał pontyfikat Jana Pawła II — drugi najdłuższy w nowożytnej historii?',
    answer: 26,
    unit: 'lat',
    hint: 'Karol Wojtyła: 16 X 1978 – 2 IV 2005; dłuższy miał tylko Pius IX (31 lat, 1846–1878)',
  },

  // --- Skrajności i rekordy różne ---
  {
    id: 'hl185',
    text: 'Ile metrów głębokości osiągnął James Cameron zanurkowując solo do Rowu Mariańskiego (2012)?',
    answer: 10908,
    unit: 'metrów',
    hint: 'Misja Deepsea Challenger, 26 III 2012; Cameron spędził 3 godziny na dnie; nakręcił materiał dla National Geographic',
  },
  {
    id: 'hl186',
    text: 'Ile km/h osiągnął Felix Baumgartner podczas stratosferycznego skoku ze 128 km wysokości (2012) — bijąc barierę dźwięku?',
    answer: 1357,
    unit: 'km/h',
    hint: 'Projekt Red Bull Stratos; Mach 1,25; najszybszy człowiek w wolnym locie; po 4 min 20 s otworzył spadochron',
  },
  {
    id: 'hl187',
    text: 'Ile km/s porusza się Ziemia krążąc po orbicie wokół Słońca?',
    answer: 30,
    unit: 'km/s',
    hint: 'Dokładnie ok. 29,8 km/s = 107 000 km/h; jedno okrążenie Słońca zajmuje 365,25 dnia',
  },
  {
    id: 'hl188',
    text: 'Ile metrów n.p.m. ma Chimborazo w Ekwadorze — góra, której szczyt jest geometrycznie najdalej od centrum Ziemi?',
    answer: 6263,
    unit: 'm n.p.m.',
    hint: 'Choć niższe od Everestu o ~2 600 m, leży blisko równika (gdzie Ziemia „puchnie"); szczyt Chimborazo jest 6 384 km od centrum Ziemi vs. Everest 6 382 km',
  },
  {
    id: 'hl189',
    text: 'Ile procent wszystkich gatunków, które kiedykolwiek żyły na Ziemi, jest dziś wymarłych?',
    answer: 99,
    unit: '%',
    hint: 'Szacunki paleontologów: >99,9%; pięć wielkich wymierań; aktualne — 6. wielkie wymieranie — właśnie trwa',
  },
  {
    id: 'hl190',
    text: 'Ile km liczy rzeka Amazonka — największa pod względem przepływu wody rzeka świata?',
    answer: 6400,
    unit: 'km',
    hint: 'Tradycyjnie: Nil 6 650 km > Amazonka 6 400 km, ale Amazonka ma przepływ wody 5× większy niż Nil',
  },

  // --- Dzieci i rodzicielstwo ---
  {
    id: 'hl191',
    text: 'Ile dzieci rodzi statystycznie Polka w ciągu całego życia (współczynnik dzietności TFR, GUS 2022)?',
    answer: 1.26,
    unit: 'dziecka',
    hint: 'Jeden z najniższych wskaźników w UE; dla prostej zastępowalności pokoleń potrzeba TFR = 2,1',
  },
  {
    id: 'hl192',
    text: 'Ile lat ma przeciętna Polka, kiedy rodzi pierwsze dziecko (GUS 2022)?',
    answer: 28,
    unit: 'lat',
    hint: 'Wzrost z 23 lat w 1990 r.; trend coraz późniejszego macierzyństwa trwa w całej Europie',
  },
  {
    id: 'hl193',
    text: 'Ile dzieci urodziło się w Polsce w 2022 roku?',
    answer: 305000,
    unit: 'dzieci',
    hint: 'GUS 2022; najniższy wynik od II wojny światowej; w 1983 r. urodziło się ponad 700 000 dzieci',
  },
  {
    id: 'hl194',
    text: 'Ile procent dzieci w Polsce rodzi się poza małżeństwem (GUS 2022)?',
    answer: 28,
    unit: '%',
    hint: 'Wzrost z 5% w 1990 r.; w Danii i Francji to ponad 60%; w Polsce tendencja rosnąca',
  },
  {
    id: 'hl195',
    text: 'Ile złotych kosztuje wychowanie dziecka w Polsce od narodzin do 18. roku życia (szacunki ekonomistów)?',
    answer: 250000,
    unit: 'zł',
    hint: 'Szacunki PKO BP i innych instytucji: 200 000–300 000 zł; bez kosztów studiów i wesela',
  },
  {
    id: 'hl196',
    text: 'Ile porodów na 1 000 kończy się urodzeniem bliźniąt?',
    answer: 13,
    unit: 'na 1 000 porodów',
    hint: 'Globalna średnia; wzrost przez in vitro — wcześniej ok. 8/1 000; w Polsce bliźnięta rodzą się co ~75 porodów',
  },
  {
    id: 'hl197',
    text: 'Ile procent par w Polsce zmaga się z problemem niepłodności?',
    answer: 20,
    unit: '%',
    hint: 'Szacunki Polskiego Towarzystwa Ginekologicznego: co 5. para; główne przyczyny: stres, otyłość, odkładanie ciąży',
  },
  {
    id: 'hl198',
    text: 'Ile kg waży przeciętny noworodek przy urodzeniu?',
    answer: 3.3,
    unit: 'kg',
    hint: 'Norma WHO: 2,5–4,0 kg; poniżej 2,5 kg = niska masa urodzeniowa; powyżej 4,0 kg = makrosomia',
  },
  {
    id: 'hl199',
    text: 'Ile cm mierzy przeciętny noworodek w chwili urodzenia?',
    answer: 50,
    unit: 'cm',
    hint: 'Norma: 48–52 cm; w pierwszym roku życia dziecko urośnie o ok. 25 cm, osiągając ~75 cm',
  },
  {
    id: 'hl200',
    text: 'Ile zębów mlecznych wyrasta dziecku do 3. roku życia?',
    answer: 20,
    unit: 'zębów',
    hint: '4 siekacze górne + 4 dolne + 4 kły + 8 trzonowców; wypadają między 6. a 12. rokiem życia',
  },

  // --- Związki i miłość ---
  {
    id: 'hl201',
    text: 'Ile dni od pierwszego spotkania mężczyzna mówi "kocham cię" jako pierwszy wg. badań psychologicznych?',
    answer: 88,
    unit: 'dni',
    hint: 'Kobiety czekają średnio ok. 134 dni; mężczyźni deklarują uczucia szybciej, ale rzadziej jako pierwsi inicjują rozmowę o związku',
  },
  {
    id: 'hl202',
    text: 'Ile miliardów przesunięć (swipe) dziennie rejestruje aplikacja Tinder na całym świecie?',
    answer: 2,
    unit: 'mld swipe\'ów/dzień',
    hint: 'Tinder działa w 190 krajach; w Polsce to jedna z najpopularniejszych aplikacji randkowych',
  },
  {
    id: 'hl203',
    text: 'Ile miliardów dolarów wydają Amerykanie na Walentynki w ciągu jednego roku (National Retail Federation 2023)?',
    answer: 24,
    unit: 'mld USD',
    hint: 'Rekordy biją biżuteria, kolacja na mieście i kwiaty; w Polsce Walentynki to rynek wart ok. 500 mln zł',
  },
  {
    id: 'hl204',
    text: 'Ile procent par w USA poznało się przez internet (badanie Stanford, 2019)?',
    answer: 39,
    unit: '%',
    hint: 'Badanie Rosenfelda i in.; w 2009 r. było to 22%; prognozy na 2025: ponad 50%; trend globalny',
  },
  {
    id: 'hl205',
    text: 'Ile milionów aktywnych użytkowników ma Tinder miesięcznie na całym świecie?',
    answer: 75,
    unit: 'mln użytkowników',
    hint: 'Match Group 2022; właściciel posiada też Hinge, OkCupid, Match.com; łącznie: ponad 40 aplikacji',
  },
  {
    id: 'hl206',
    text: 'Ile lat statystycznie para spotyka się przed zaręczynami?',
    answer: 3,
    unit: 'lat',
    hint: 'Badanie WeddingWire: dokładnie 2,8 roku; po zaręczynach do ślubu: średnio jeszcze ok. 14 miesięcy',
  },
  {
    id: 'hl207',
    text: 'Ile procent osób w stałym związku kiedykolwiek zdradziło partnera (General Social Survey, USA)?',
    answer: 20,
    unit: '%',
    hint: 'Co piąta osoba; mężczyźni: ~20%, kobiety: ~13%; w Polsce wg. CBOS: podobne wyniki',
  },
  {
    id: 'hl208',
    text: 'Ile lat trwa statystycznie faza intensywnego zakochania (tzw. limerence), zanim przejdzie w spokojniejszą miłość?',
    answer: 2,
    unit: 'lat',
    hint: 'Badania Helen Fisher (Rutgers Univ.); po ok. 2 latach mózg "wychodzi" z euforycznego stanu i oxytocyna zastępuje dopaminę',
  },
  {
    id: 'hl209',
    text: 'Ile procent wniosków rozwodowych w USA składają kobiety (Stanford Law School, 2015)?',
    answer: 70,
    unit: '%',
    hint: 'Badanie Michaela Rosenfelda; wśród par bez ślubu kobiety inicjują rozstanie jeszcze częściej (~75%)',
  },
  {
    id: 'hl210',
    text: 'Ile procent małżeństw w USA kończy się rozwodem (American Psychological Association)?',
    answer: 41,
    unit: '%',
    hint: 'Popularny mit mówi o 50% — rzeczywisty wskaźnik to 40–42%; w Polsce: ok. 33%',
  },

  // --- Seks ---
  {
    id: 'hl211',
    text: 'Ile razy w roku uprawia seks statystyczna para w stałym związku (Durex Global Sex Survey)?',
    answer: 54,
    unit: 'razy/rok',
    hint: 'Czyli ok. raz w tygodniu; wzrost aktywności seksualnej: wiek 25–35; po 50. roku życia spada',
  },
  {
    id: 'hl212',
    text: 'Ile razy rocznie uprawiają seks Grecy — naród na pierwszym miejscu rankingu Durex Global Sex Survey?',
    answer: 164,
    unit: 'razy/rok',
    hint: 'Dla porównania: Japonia: 45 razy/rok; Niemcy: 117; Polska: ok. 98; globalnie: 54',
  },
  {
    id: 'hl213',
    text: 'Ile lat mają Polacy przeciętnie podczas inicjacji seksualnej (CBOS 2019)?',
    answer: 18,
    unit: 'lat',
    hint: 'Dane CBOS; wiek inicjacji seksualnej w Polsce pozostaje stabilny od lat; w Europie: od 16 do 19 lat zależnie od kraju',
  },
  {
    id: 'hl214',
    text: 'Ile minut trwa przeciętna gra wstępna przed stosunkiem wg. Journal of Sexual Medicine?',
    answer: 11,
    unit: 'minut',
    hint: 'Badanie Waldingera i in. (2005); kobiety preferują dłuższą grę wstępną; wpływa na osiąganie orgazmu',
  },
  {
    id: 'hl215',
    text: 'Ile procent dorosłych miało przynajmniej raz w życiu seks przelotny — one-night stand (YouGov 2014)?',
    answer: 46,
    unit: '%',
    hint: 'Badanie YouGov UK; mężczyźni: 55%, kobiety: 38%; wiek szczytowy: 25–34 lata',
  },
  {
    id: 'hl216',
    text: 'Ile miliardów dolarów wynosi globalny rynek zabawek erotycznych (2023)?',
    answer: 35,
    unit: 'mld USD',
    hint: 'Grand View Research 2023: ok. 35–36 mld USD; wzrost po pandemii o ponad 30%; liderzy: USA, Niemcy, Japonia',
  },
  {
    id: 'hl217',
    text: 'Ile razy dziennie statystyczny mężczyzna myśli o seksie wg. badania Ohio State University (2011)?',
    answer: 19,
    unit: 'razy/dzień',
    hint: 'Obalono mit "co 7 sekund" = 8 000 razy/dobę; w tym samym badaniu kobiety: ok. 10 razy dziennie',
  },
  {
    id: 'hl218',
    text: 'O ile cm jest wyższy mężczyzna od kobiety w przeciętnej heteroseksualnej parze (badanie Stulp i in., 2013)?',
    answer: 14,
    unit: 'cm',
    hint: 'Biology Letters, 2013; kobiety preferują partnerów wyższych od siebie o ok. 17–20 cm; mężczyźni wolą kobiety niższe o ok. 8 cm',
  },
  {
    id: 'hl219',
    text: 'Ile milisekund wystarczy ludzkiemu mózgowi, by wyrobić pierwsze wrażenie o nowej osobie (Willis & Todorov, 2006)?',
    answer: 100,
    unit: 'milisekund',
    hint: 'Psychological Science 2006; w ciągu 1/10 sekundy oceniamy atrakcyjność, wiarygodność i kompetencje rozmówcy',
  },
  {
    id: 'hl220',
    text: 'Ile procent osób wróciło przynajmniej raz do byłego partnera lub partnerki (YouGov 2017)?',
    answer: 44,
    unit: '%',
    hint: 'Badanie YouGov; najczęstszy powód powrotu: tęsknota i przekonanie, że się zmienili; połowa żałuje powrotu',
  },

  // --- Świat i państwa ---
  {
    id: 'hl221',
    text: 'Ile państw jest członkami Organizacji Narodów Zjednoczonych (2024)?',
    answer: 193,
    unit: 'państw',
    hint: 'Ostatni przyjęty: Sudan Południowy (2011); Watykan i Palestyna mają status obserwatora',
  },
  {
    id: 'hl222',
    text: 'Ile państw leży na kontynencie afrykańskim?',
    answer: 54,
    unit: 'państw',
    hint: 'Najwięcej ze wszystkich kontynentów; najludniejsze: Nigeria (ponad 220 mln mieszkańców)',
  },
  {
    id: 'hl223',
    text: 'Ile km² powierzchni ma Watykan — najmniejsze państwo świata?',
    answer: 0.49,
    unit: 'km²',
    hint: 'Ok. 49 hektarów; ludność ok. 800 osób; mieści się w granicach Rzymu',
  },
  {
    id: 'hl224',
    text: 'Ile miliardów ludzi liczy populacja Chin (2023)?',
    answer: 1.4,
    unit: 'mld osób',
    hint: 'Dokładnie ok. 1,41 mld; w 2023 r. Indie wyprzedziły Chiny jako najludniejszy kraj świata',
  },
  {
    id: 'hl225',
    text: 'Ile miliardów ludzi liczy populacja całego świata (2023)?',
    answer: 8,
    unit: 'mld osób',
    hint: 'Granicę 8 mld przekroczono 15 listopada 2022 r. wg ONZ; w 1950 r. było to 2,5 mld',
  },
  {
    id: 'hl226',
    text: 'Ile języków używanych jest obecnie na świecie?',
    answer: 7000,
    unit: 'języków',
    hint: 'Baza Ethnologue: ok. 7 100; niemal połowa jest zagrożona wymarciem',
  },
  {
    id: 'hl227',
    text: 'Ile km wysokości ma Olympus Mons na Marsie — najwyższa góra Układu Słonecznego?',
    answer: 22,
    unit: 'km',
    hint: 'Wulkan tarczowy, ok. 2,5× wyższy od Mount Everestu; podstawa wielkości Polski',
  },
  {
    id: 'hl228',
    text: 'Ile km liczy obwód Ziemi mierzony wzdłuż równika?',
    answer: 40075,
    unit: 'km',
    hint: 'Obwód południkowy (przez bieguny) jest nieco krótszy: 40 008 km — Ziemia jest spłaszczona',
  },

  // --- Zwierzęta II ---
  {
    id: 'hl229',
    text: 'Ile serc ma ośmiornica?',
    answer: 3,
    unit: 'serca',
    hint: 'Dwa serca skrzelowe + jedno główne; krew jest niebieska dzięki hemocyjaninie',
  },
  {
    id: 'hl230',
    text: 'Ile par "serc" (łuków aortalnych) ma dżdżownica?',
    answer: 5,
    unit: 'par serc',
    hint: 'Pięć par pulsujących naczyń pełni rolę serca; dżdżownica nie ma płuc — oddycha skórą',
  },
  {
    id: 'hl231',
    text: 'Ile komór ma żołądek krowy?',
    answer: 4,
    unit: 'komory',
    hint: 'Żwacz, czepiec, księgi i trawieniec; przeżuwacz fermentuje trawę z pomocą mikroorganizmów',
  },
  {
    id: 'hl232',
    text: 'Ile jaj składa królowa pszczół w ciągu jednej doby w szczycie sezonu?',
    answer: 2000,
    unit: 'jaj/dobę',
    hint: 'To więcej niż masa jej własnego ciała; żyje 3–5 lat, robotnice tylko kilka tygodni',
  },
  {
    id: 'hl233',
    text: 'Ile lat może dożyć papuga ara?',
    answer: 50,
    unit: 'lat',
    hint: 'W niewoli nawet 60–80 lat; należą do najdłużej żyjących ptaków',
  },
  {
    id: 'hl234',
    text: 'Ile km pokonuje rybitwa popielata podczas jednej rocznej migracji (tam i z powrotem)?',
    answer: 70000,
    unit: 'km',
    hint: 'Najdłuższa migracja w świecie zwierząt; lata od Arktyki po Antarktydę i z powrotem',
  },
  {
    id: 'hl235',
    text: 'Ile gramów waży koliber hawański — najmniejszy ptak świata?',
    answer: 2,
    unit: 'gramów',
    hint: 'Mniej niż moneta 5 gr; bije skrzydłami ok. 80 razy na sekundę',
  },
  {
    id: 'hl236',
    text: 'Ile gatunków ssaków opisano na Ziemi?',
    answer: 6400,
    unit: 'gatunków',
    hint: 'American Society of Mammalogists; nowe gatunki (zwłaszcza nietoperze i gryzonie) odkrywa się co roku',
  },
  {
    id: 'hl237',
    text: 'Ile zębów ma jednocześnie w pysku żarłacz biały (rekin ludojad)?',
    answer: 300,
    unit: 'zębów',
    hint: 'Ułożone w kilku rzędach; przez całe życie rekin zużywa ich tysiące — odrastają bez przerwy',
  },
  {
    id: 'hl238',
    text: 'Ile kolców ma przeciętny jeż europejski?',
    answer: 6000,
    unit: 'kolców',
    hint: 'Zakres 5 000–7 000; każdy kolec żyje ok. roku i wypada, zastępowany nowym',
  },

  // --- Ludzkie ciało II ---
  {
    id: 'hl239',
    text: 'Ile pęcherzyków płucnych (alweol) ma człowiek w obu płucach?',
    answer: 300000000,
    unit: 'pęcherzyków',
    hint: 'Ich łączna powierzchnia wymiany gazowej to ok. 70 m² — wielkość kortu do squasha',
  },
  {
    id: 'hl240',
    text: 'Ile kubków smakowych ma język dorosłego człowieka?',
    answer: 10000,
    unit: 'kubków smakowych',
    hint: 'Regenerują się co ok. 10 dni; z wiekiem ich liczba spada — stąd słabnący smak u seniorów',
  },
  {
    id: 'hl241',
    text: 'Ile litrów śliny produkuje człowiek w ciągu doby?',
    answer: 1.5,
    unit: 'litra',
    hint: 'Przez całe życie to ok. 40 000 litrów — tyle zmieściłoby się w basenie',
  },
  {
    id: 'hl242',
    text: 'Ile litrów powietrza wdycha człowiek w ciągu jednej doby?',
    answer: 11000,
    unit: 'litrów',
    hint: 'Ok. 11 m³; w spoczynku jeden wdech to ok. 0,5 l, a oddychamy ok. 20 000 razy dziennie',
  },
  {
    id: 'hl243',
    text: 'Ile mięśni porusza jedną gałką oczną człowieka?',
    answer: 6,
    unit: 'mięśni',
    hint: 'Mięśnie okoruchowe to jedne z najszybszych w ciele; oko wykonuje setki ruchów na minutę',
  },
  {
    id: 'hl244',
    text: 'Ile razy dziennie przeciętny człowiek oddaje gazy jelitowe?',
    answer: 15,
    unit: 'razy',
    hint: 'Norma to 10–20 razy; gaz powstaje głównie przez bakterie fermentujące pokarm w jelicie grubym',
  },
  {
    id: 'hl245',
    text: 'Ile bilionów komórek tworzy ludzkie ciało?',
    answer: 37,
    unit: 'bilionów komórek',
    hint: 'Badanie Bianconi et al. (2013): ok. 37,2 biliona; najwięcej z nich to czerwone krwinki',
  },
  {
    id: 'hl246',
    text: 'Ile bilionów bakterii żyje w jelitach jednego człowieka (mikrobiom)?',
    answer: 39,
    unit: 'bilionów bakterii',
    hint: 'Jest ich więcej niż własnych komórek ciała; ważą łącznie ok. 1,5–2 kg',
  },
  {
    id: 'hl247',
    text: 'Ile dni trwa pełna wymiana zewnętrznej warstwy naskórka u człowieka?',
    answer: 27,
    unit: 'dni',
    hint: 'Złuszczamy ok. 30 000–40 000 martwych komórek skóry na minutę; większość kurzu domowego to skóra',
  },
  {
    id: 'hl248',
    text: 'Ile kg waży ludzka wątroba — największy narząd wewnętrzny?',
    answer: 1.5,
    unit: 'kg',
    hint: 'Jedyny narząd zdolny do samoregeneracji; pełni ponad 500 różnych funkcji',
  },

  // --- Technologia i internet II ---
  {
    id: 'hl249',
    text: 'Ile miliardów tranzystorów ma procesor Apple M1 (2020)?',
    answer: 16,
    unit: 'mld tranzystorów',
    hint: 'Wyprodukowany w procesie 5 nm; pierwszy procesor Apple dla komputerów Mac na architekturze ARM',
  },
  {
    id: 'hl250',
    text: 'Ile zdjęć wrzucanych jest na Instagram każdego dnia?',
    answer: 95,
    unit: 'mln zdjęć/dzień',
    hint: 'Łącznie ze Stories i Reels liczba postów jest jeszcze wyższa; aplikacja ma ponad 2 mld użytkowników',
  },
  {
    id: 'hl251',
    text: 'Ile miliardów e-maili wysyłanych jest na świecie każdego dnia?',
    answer: 330,
    unit: 'mld maili/dzień',
    hint: 'Dane Statista 2022; znaczną część stanowi spam i wiadomości automatyczne',
  },
  {
    id: 'hl252',
    text: 'Ile miliardów wyszukiwań obsługuje Google każdego dnia?',
    answer: 8.5,
    unit: 'mld wyszukiwań/dzień',
    hint: 'To ok. 99 000 zapytań na sekundę; Google ma ponad 90% udziału w rynku wyszukiwarek',
  },
  {
    id: 'hl253',
    text: 'Ile miliardów aktywnych użytkowników miesięcznie ma Facebook (2023)?',
    answer: 3,
    unit: 'mld użytkowników',
    hint: 'Dane Meta Q4 2023; to ponad 1/3 ludzkości; najpopularniejsza sieć społecznościowa świata',
  },
  {
    id: 'hl254',
    text: 'Ile GB danych zużywa godzina oglądania Netflixa w jakości 4K?',
    answer: 7,
    unit: 'GB/godzinę',
    hint: 'Jakość HD to ok. 3 GB/godz., a SD tylko ok. 1 GB/godz.',
  },
  {
    id: 'hl255',
    text: 'Ile milionów postów publikowanych jest dziennie na platformie X (dawniej Twitter)?',
    answer: 500,
    unit: 'mln postów/dzień',
    hint: 'Ok. 6 000 postów na sekundę; rekordy biją wielkie wydarzenia sportowe i wybory',
  },
  {
    id: 'hl256',
    text: 'Ile milionów aplikacji dostępnych jest w sklepie Google Play (2023)?',
    answer: 2.6,
    unit: 'mln aplikacji',
    hint: 'Apple App Store ma ich ok. 1,8 mln; większość aplikacji jest darmowych',
  },

  // --- Jedzenie i napoje II ---
  {
    id: 'hl257',
    text: 'Ile litrów piwa wypija statystyczny Czech w ciągu roku — najwięcej na świecie?',
    answer: 180,
    unit: 'litrów/rok',
    hint: 'Czesi są liderami od ponad 30 lat; Polska: ok. 100 l, Niemcy: ok. 95 l rocznie',
  },
  {
    id: 'hl258',
    text: 'Ile miliardów filiżanek kawy wypija świat każdego dnia?',
    answer: 2,
    unit: 'mld filiżanek/dzień',
    hint: 'Ok. 2,25 mld; kawa to po ropie naftowej drugi najczęściej handlowany towar na świecie',
  },
  {
    id: 'hl259',
    text: 'Ile kilokalorii dostarcza 1 gram tłuszczu?',
    answer: 9,
    unit: 'kcal/g',
    hint: 'Białko i węglowodany dają po 4 kcal/g, a alkohol 7 kcal/g; tłuszcz jest najbardziej kaloryczny',
  },
  {
    id: 'hl260',
    text: 'Ile miesięcy leżakuje się typowy ser Parmigiano Reggiano?',
    answer: 24,
    unit: 'miesięcy',
    hint: 'Minimum 12 miesięcy; odmiany premium dojrzewają nawet 36–48 miesięcy',
  },
  {
    id: 'hl261',
    text: 'Ile łyżeczek cukru dziennie zaleca jako maksimum Światowa Organizacja Zdrowia (WHO)?',
    answer: 6,
    unit: 'łyżeczek',
    hint: 'To ok. 25 g cukrów wolnych; jedna puszka coli przekracza ten limit o ok. 40%',
  },
  {
    id: 'hl262',
    text: 'Ile kilokalorii ma przeciętne jabłko (ok. 150 g)?',
    answer: 80,
    unit: 'kcal',
    hint: 'Składa się w ok. 85% z wody; bogate w błonnik i witaminę C',
  },

  // --- Sport II ---
  {
    id: 'hl263',
    text: 'Ile minut trwa regulaminowy mecz koszykówki w lidze NBA?',
    answer: 48,
    unit: 'minut',
    hint: 'Cztery kwarty po 12 minut; w rozgrywkach FIBA i olimpijskich mecz trwa 40 minut',
  },
  {
    id: 'hl264',
    text: 'Ile gramów waży piłka do koszykówki rozmiaru 7 (męska)?',
    answer: 600,
    unit: 'gramów',
    hint: 'Zakres 567–650 g; obwód ok. 75 cm; piłka damska (rozmiar 6) jest lżejsza',
  },
  {
    id: 'hl265',
    text: 'Ile razy reprezentacja Brazylii wygrała piłkarskie Mistrzostwa Świata?',
    answer: 5,
    unit: 'razy',
    hint: 'Lata 1958, 1962, 1970, 1994 i 2002; rekordzista turnieju; jako jedyni grali we wszystkich edycjach',
  },
  {
    id: 'hl266',
    text: 'Ile okrążeń liczy wyścig Formuły 1 o Grand Prix Monako?',
    answer: 78,
    unit: 'okrążeń',
    hint: 'Najwolniejszy i najbardziej prestiżowy tor w kalendarzu; wąskie uliczki Monte Carlo',
  },
  {
    id: 'hl267',
    text: 'Ile dołków ma standardowe pole golfowe?',
    answer: 18,
    unit: 'dołków',
    hint: 'Pełna runda; standard ustalił klub St Andrews w Szkocji w 1764 r.',
  },
  {
    id: 'hl268',
    text: 'Ile kg waży kula używana w męskim pchnięciu kulą?',
    answer: 7.26,
    unit: 'kg',
    hint: 'Dokładnie 7,26 kg (16 funtów); kula kobieca waży 4 kg',
  },
  {
    id: 'hl269',
    text: 'Ile gramów waży piłka tenisowa?',
    answer: 57,
    unit: 'gramów',
    hint: 'Dopuszczalny zakres 56,0–59,4 g; średnica ok. 6,7 cm; żółty kolor wprowadzono w 1972 r.',
  },
  {
    id: 'hl270',
    text: 'Ile kolarzy startuje przeciętnie w wyścigu Tour de France?',
    answer: 176,
    unit: 'kolarzy',
    hint: '22 ekipy po 8 zawodników; do mety dojeżdża zwykle ok. 140–150 z nich',
  },

  // --- Film i telewizja II ---
  {
    id: 'hl271',
    text: 'Ile odcinków wyemitowano serialu Simpsonowie (stan 2024)?',
    answer: 750,
    unit: 'odcinków',
    hint: 'Najdłuższy serial fabularny w historii amerykańskiej telewizji; premiera w 1989 r.',
  },
  {
    id: 'hl272',
    text: 'Ile Oscarów zdobył film Władca Pierścieni: Powrót króla (2004)?',
    answer: 11,
    unit: 'Oscarów',
    hint: 'Wygrał wszystkie 11 nominacji; rekord ex aequo z filmami Titanic i Ben-Hur',
  },
  {
    id: 'hl273',
    text: 'Ile miliardów dolarów zarobił w kinach film Avengers: Koniec gry (2019)?',
    answer: 2.8,
    unit: 'mld USD',
    hint: 'Ok. 2,799 mld USD; przez pewien czas najbardziej dochodowy film w historii, wyprzedzony przez Avatara',
  },
  {
    id: 'hl274',
    text: 'Ile sezonów liczy serial Gra o tron?',
    answer: 8,
    unit: 'sezonów',
    hint: '73 odcinki w latach 2011–2019; finałowy sezon wzbudził rekordowe kontrowersje wśród widzów',
  },
  {
    id: 'hl275',
    text: 'Ile minut trwa film Titanic Jamesa Camerona (1997)?',
    answer: 194,
    unit: 'minut',
    hint: 'Ponad 3 godziny; zdobył 11 Oscarów i przez 12 lat był najbardziej dochodowym filmem świata',
  },
  {
    id: 'hl276',
    text: 'Ile lat miała Tatum ONeal, gdy została najmłodszą laureatką Oscara dla aktorki?',
    answer: 10,
    unit: 'lat',
    hint: 'Nagroda za film Papierowy księżyc (1974); rekord najmłodszej zdobywczyni do dziś niepobity',
  },

  // --- Historia II ---
  {
    id: 'hl277',
    text: 'Ile lat trwała wojna stuletnia między Anglią a Francją?',
    answer: 116,
    unit: 'lat',
    hint: 'Mimo nazwy trwała 1337–1453; bohaterką jej końcowej fazy była Joanna dArc',
  },
  {
    id: 'hl278',
    text: 'Ile minut trwała wojna brytyjsko-zanzibarska (1896) — najkrótsza wojna w historii?',
    answer: 38,
    unit: 'minut',
    hint: '27 sierpnia 1896 r.; figuruje w Księdze rekordów Guinnessa; flota brytyjska ostrzelała pałac sułtana',
  },
  {
    id: 'hl279',
    text: 'Ile piramid odkryto dotychczas w Egipcie?',
    answer: 118,
    unit: 'piramid',
    hint: 'Najsłynniejsze w Gizie; najstarsza to schodkowa piramida Dżesera w Sakkarze (ok. 2670 p.n.e.)',
  },
  {
    id: 'hl280',
    text: 'Ile lat panował Ludwik XIV — najdłużej rządzący monarcha w historii Europy?',
    answer: 72,
    unit: 'lat',
    hint: 'Król Słońce zasiadał na tronie Francji w latach 1643–1715; zbudował pałac w Wersalu',
  },
  {
    id: 'hl281',
    text: 'Ile statków wyruszyło z Krzysztofem Kolumbem w jego pierwszej wyprawie do Ameryki (1492)?',
    answer: 3,
    unit: 'statki',
    hint: 'Santa María, Pinta i Niña; ląd zobaczono 12 października 1492 r.',
  },
  {
    id: 'hl282',
    text: 'Ile lat istniało cesarstwo zachodniorzymskie (od 27 p.n.e. do 476 n.e.)?',
    answer: 503,
    unit: 'lat',
    hint: 'Od Oktawiana Augusta do detronizacji Romulusa Augustulusa; cesarstwo wschodnie przetrwało do 1453 r.',
  },
  {
    id: 'hl283',
    text: 'Ile milionów ludzi w Europie zabiła epidemia "czarnej śmierci" (dżumy) w latach 1347–1351?',
    answer: 50,
    unit: 'mln osób',
    hint: 'Ok. 1/3 ówczesnej ludności Europy; roznosiły ją pchły żyjące na szczurach',
  },
  {
    id: 'hl284',
    text: 'Ile lat miała Kleopatra w chwili śmierci?',
    answer: 39,
    unit: 'lat',
    hint: 'Ostatnia władczyni Egiptu z dynastii Ptolemeuszy; zmarła w 30 r. p.n.e.',
  },

  // --- Ekonomia II ---
  {
    id: 'hl285',
    text: 'Ile bilionów dolarów wynosiła kapitalizacja firmy Apple, gdy jako pierwsza przekroczyła ten próg?',
    answer: 3,
    unit: 'bln USD',
    hint: 'Pierwsza spółka świata warta ponad 3 biliony USD; wcześniej, w 2018 r., przebiła 1 bln',
  },
  {
    id: 'hl286',
    text: 'Ile ton złota przechowują w rezerwach Stany Zjednoczone — najwięcej na świecie?',
    answer: 8133,
    unit: 'ton złota',
    hint: 'Większość spoczywa w Fort Knox; drugie miejsce zajmują Niemcy (ok. 3 350 ton)',
  },

  // --- Kosmos II ---
  {
    id: 'hl287',
    text: 'Ile księżyców ma Jowisz (stan 2023)?',
    answer: 95,
    unit: 'księżyców',
    hint: 'W 2023 r. Saturn wyprzedził Jowisza, osiągając 146 potwierdzonych księżyców',
  },
  {
    id: 'hl288',
    text: 'Ile głównych pierścieni (grup) ma Saturn?',
    answer: 7,
    unit: 'pierścieni',
    hint: 'Oznaczono je literami od A do G; zbudowane są z miliardów kawałków lodu i skał',
  },
  {
    id: 'hl289',
    text: 'Ile dni ziemskich trwa rok (pełny obieg wokół Słońca) na Merkurym?',
    answer: 88,
    unit: 'dni',
    hint: 'Najszybciej krążąca planeta; jego doba (obrót) jest jednak dłuższa niż rok',
  },
  {
    id: 'hl290',
    text: 'Ile stopni Celsjusza wynosi temperatura na powierzchni Wenus — najgorętszej planety?',
    answer: 465,
    unit: '°C',
    hint: 'Gęsta atmosfera CO₂ powoduje ekstremalny efekt cieplarniany; goręcej niż na Merkurym, mimo dalszej orbity',
  },
  {
    id: 'hl291',
    text: 'Ile planet liczy Układ Słoneczny (po reklasyfikacji z 2006 roku)?',
    answer: 8,
    unit: 'planet',
    hint: 'Pluton został w 2006 r. uznany za planetę karłowatą decyzją Międzynarodowej Unii Astronomicznej',
  },
  {
    id: 'hl292',
    text: 'Ile stopni Celsjusza wynosi temperatura tła kosmicznego (najniższa w przestrzeni)?',
    answer: -270,
    unit: '°C',
    hint: '2,7 kelwina — pozostałość promieniowania reliktowego po Wielkim Wybuchu',
  },

  // --- Natura i rośliny ---
  {
    id: 'hl293',
    text: 'Ile metrów wysokości ma Hyperion — najwyższe drzewo świata (sekwoja, Kalifornia)?',
    answer: 116,
    unit: 'metrów',
    hint: 'Odkryte w 2006 r.; jego dokładna lokalizacja jest utajniona dla ochrony drzewa',
  },
  {
    id: 'hl294',
    text: 'Ile lat może żyć dąb szypułkowy?',
    answer: 1000,
    unit: 'lat',
    hint: 'Niektóre okazy przekraczają 1 500 lat; polski Dąb Bartek ma ok. 700 lat',
  },
  {
    id: 'hl295',
    text: 'Ile gatunków roślin opisano dotychczas na Ziemi?',
    answer: 390000,
    unit: 'gatunków',
    hint: 'Dane Royal Botanic Gardens, Kew; co roku odkrywa się ok. 2 000 nowych gatunków',
  },
  {
    id: 'hl296',
    text: 'Ile cm na dobę potrafi urosnąć bambus — najszybciej rosnąca roślina świata?',
    answer: 90,
    unit: 'cm/dobę',
    hint: 'Rekord Guinnessa to ok. 91 cm w jeden dzień; przyrost słychać czasem jako trzaski',
  },

  // --- Język i wiedza ---
  {
    id: 'hl297',
    text: 'Ile liter ma polski alfabet?',
    answer: 32,
    unit: 'liter',
    hint: '9 samogłosek i 23 spółgłoski; nie zawiera liter Q, V ani X (poza wyrazami obcymi)',
  },
  {
    id: 'hl298',
    text: 'Ile znaków trzeba znać, by swobodnie czytać chińską gazetę?',
    answer: 3000,
    unit: 'znaków',
    hint: 'Słownik Kangxi opisuje ok. 47 000 znaków; przeciętny wykształcony Chińczyk zna ok. 8 000',
  },
  {
    id: 'hl299',
    text: 'Ile języków urzędowych ma Organizacja Narodów Zjednoczonych?',
    answer: 6,
    unit: 'języków',
    hint: 'Angielski, francuski, hiszpański, rosyjski, chiński i arabski; polski nie jest wśród nich',
  },

  // --- Polska II ---
  {
    id: 'hl300',
    text: 'Ile lat trwa kadencja Prezydenta RP?',
    answer: 5,
    unit: 'lat',
    hint: 'Tę samą osobę można wybrać maksymalnie na dwie kadencje',
  },
  {
    id: 'hl301',
    text: 'Ilu posłów zasiada w Sejmie RP?',
    answer: 460,
    unit: 'posłów',
    hint: 'Senat liczy 100 senatorów; razem tworzą Zgromadzenie Narodowe',
  },
  {
    id: 'hl302',
    text: 'Ile województw ma Polska?',
    answer: 16,
    unit: 'województw',
    hint: 'Podział wprowadziła reforma administracyjna z 1999 r.; wcześniej było ich 49',
  },

  // --- Zwierzęta III: sen i serce ---
  {
    id: 'hl303',
    text: 'Ile razy na minutę bije serce myszy?',
    answer: 600,
    unit: 'uderzeń/min',
    hint: 'Im mniejsze zwierzę, tym szybsze tętno; serce słonia bije ok. 30 razy na minutę',
  },
  {
    id: 'hl304',
    text: 'Ile godzin na dobę śpi koala?',
    answer: 22,
    unit: 'godzin',
    hint: 'Liście eukaliptusa są tak ubogie w energię i toksyczne, że trawienie wymaga oszczędzania sił',
  },
  {
    id: 'hl305',
    text: 'Ile godzin na dobę śpi żyrafa?',
    answer: 2,
    unit: 'godzin',
    hint: 'Jeden z najkrótszych snów wśród ssaków; często drzemie na stojąco, by szybko uciec drapieżnikom',
  },
  {
    id: 'hl306',
    text: 'Ile godzin na dobę śpi przeciętny kot domowy?',
    answer: 16,
    unit: 'godzin',
    hint: 'To ok. 70% życia; koty to drapieżniki oszczędzające energię między polowaniami',
  },
  {
    id: 'hl307',
    text: 'Ile kg waży serce płetwala błękitnego — największego zwierzęcia na Ziemi?',
    answer: 180,
    unit: 'kg',
    hint: 'Wielkości małego samochodu; jego uderzenie słychać z odległości kilku kilometrów',
  },
  {
    id: 'hl308',
    text: 'Ile razy więcej niż własna masa ciała potrafi zjeść koliber w ciągu dnia (w nektarze)?',
    answer: 2,
    unit: 'razy masę ciała',
    hint: 'Ma najszybszy metabolizm wśród kręgowców; bez jedzenia umarłby w kilka godzin',
  },

  // --- Nauka i miary ---
  {
    id: 'hl309',
    text: 'Ile kg waży jeden metr sześcienny czystej wody?',
    answer: 1000,
    unit: 'kg',
    hint: 'Czyli równo 1 tona; ta zależność legła u podstaw definicji kilograma',
  },
  {
    id: 'hl310',
    text: 'Ile m/s wynosi prędkość dźwięku w powietrzu o temperaturze 20°C?',
    answer: 343,
    unit: 'm/s',
    hint: 'To ok. 1 235 km/h; w wodzie dźwięk biegnie ponad 4× szybciej',
  },
  {
    id: 'hl311',
    text: 'Ile km/s wynosi prędkość światła w próżni?',
    answer: 300000,
    unit: 'km/s',
    hint: 'Dokładnie 299 792 km/s; światło ze Słońca dociera do Ziemi w ok. 8 minut',
  },
  {
    id: 'hl312',
    text: 'Ile pierwiastków chemicznych znajduje się w układzie okresowym (2024)?',
    answer: 118,
    unit: 'pierwiastków',
    hint: 'Ostatni to oganesson (118); najcięższe pierwiastki istnieją tylko ułamki sekundy w laboratoriach',
  },
  {
    id: 'hl313',
    text: 'Ile stopni Celsjusza wynosi temperatura zera bezwzględnego?',
    answer: -273.15,
    unit: '°C',
    hint: 'To 0 kelwinów — teoretycznie najniższa możliwa temperatura, w której ustaje ruch cząsteczek',
  },
  {
    id: 'hl314',
    text: 'Ile kości znajduje się w jednej ludzkiej dłoni (wraz z nadgarstkiem)?',
    answer: 27,
    unit: 'kości',
    hint: 'Obie dłonie zawierają ponad 1/4 wszystkich kości ciała; nadgarstek ma 8 drobnych kostek',
  },

  // --- Ciekawostki II ---
  {
    id: 'hl315',
    text: 'Ile ton waży przeciętna chmura typu cumulus?',
    answer: 500,
    unit: 'ton',
    hint: 'Mimo to unosi się w powietrzu, bo woda jest rozproszona w mikroskopijnych kropelkach',
  },
  {
    id: 'hl316',
    text: 'Ile piorunów uderza w Ziemię w ciągu jednej sekundy?',
    answer: 100,
    unit: 'piorunów/s',
    hint: 'To ok. 8 milionów wyładowań dziennie; temperatura kanału pioruna sięga 30 000°C',
  },
  {
    id: 'hl317',
    text: 'Ile minut leci światło ze Słońca do Ziemi?',
    answer: 8,
    unit: 'minut',
    hint: 'Dokładnie ok. 8 min 20 s; widzimy więc Słońce takim, jakie było 8 minut temu',
  },
  {
    id: 'hl318',
    text: 'Ile ton waży cała konstrukcja Wieży Eiffla?',
    answer: 10100,
    unit: 'ton',
    hint: 'Sama żelazna część to ok. 7 300 ton; latem wieża rośnie o ok. 15 cm z powodu rozszerzalności metalu',
  },
  {
    id: 'hl319',
    text: 'Ile schodów trzeba pokonać, by wejść na sam szczyt Wieży Eiffla?',
    answer: 1665,
    unit: 'schodów',
    hint: 'Na drugie piętro prowadzi 674 stopnie; wyżej turyści wjeżdżają już tylko windą',
  },
  {
    id: 'hl320',
    text: 'Ile milionów dolarów kosztuje 30-sekundowy spot reklamowy podczas finału Super Bowl (2023)?',
    answer: 7,
    unit: 'mln USD/30 s',
    hint: 'Mecz finałowy ligi NFL ogląda w USA ponad 100 mln widzów — to najdroższy czas reklamowy świata',
  },
  {
    id: 'hl321',
    text: 'Ile karatów ważył Cullinan — największy diament w historii (RPA, 1905)?',
    answer: 3106,
    unit: 'karatów',
    hint: 'Ponad 621 gramów surowego kamienia; pocięto go na 105 kamieni, m.in. dla brytyjskich klejnotów koronnych',
  },
  {
    id: 'hl322',
    text: 'Ile minut minęło od zderzenia z górą lodową do całkowitego zatonięcia Titanica?',
    answer: 160,
    unit: 'minut',
    hint: 'Zderzenie o 23:40, zatonięcie o 2:20 — dokładnie 2 godziny i 40 minut',
  },
]
