export const FUNNY_NAMES = [
  'Dzika Landryna',
  'Szeryfowa Rozpusta',
  'Różowa Grzesznica',
  'Kowbojka Bez Hamulców',
  'Pijana Pszczółka',
  'Królowa Tequili',
  'Neonowa Kusicielka',
  'Złota Ostroga',
  'Buntowniczka z Baru',
  'Saloonowa Bogini',
  'Whiskey Lady',
  'Galopująca Flirciara',
  'Szalona Ruda',
  'Ostra Tequila',
  'Różowy Dynamit',
  'Galopująca Panna',
  'Królowa Parkietu',
  'Wieczorowa Rozrabiara',
  'Błyszcząca Ostroga',
  'Neonowa Amazonka',
  'Gorąca Czekolada',
  'Słodka Zemsta',
  'Karmazynowa Dama',
  'Piekielna Druhna',
  'Perłowa Kokietka',
  'Rubinowa Łobuziara',
  'Ognista Panienka',
  'Niegrzeczna Blondyna',
  'Brudna Martini',
  'Kieliszkowa Królowa',
  'Wściekła Szpilka',
  'Kusicielka z Rodeo',
  'Pani Mokry Sen',
  'Dzika Suczka',
  'Barowa Królowa Dram',
  'Seksowna Szeryfka',
  'Lustereczko z Piekła',
  'Korsarzowa Kaca',
  'Panna Bez Filtra',
  'Ostra Jak Chili',
  'Błyskotka po Shotach',
  'Dama od Grzechów',
  'Cicha Uwodzicielka',
  'Głośna Awanturnica',
  'Zadziorna Kokarda',
  'Kowbojka od Kłopotów',
  'Pani Robi Hałas',
  'Barmanka Chaosu',
  'Lalunia z Las Vegas',
  'Słodka Wariatka',
  'Nocna Rakieta',
  'Pikantna Perełka',
  'Zła Księżniczka',
  'Panna Po Prosecco',
  'Królowa Walk of Shame',
  'Mistrzyni Dwuznaczności',
  'Rozpalona Iskra',
  'Pani Drama Queen',
  'Szpilka Zagłady',
  'Kieliszek Zemsty',
  'Dziewczyna z Alibi',
  'Ta od Złych Decyzji',
  'Niewinna Tylko z Wyglądu',
  'Kokietka z Kacem',
  'Szalona Flaszka',
  'Rodeo na Obcasach',
  'Królowa Niegrzecznych Myśli',
  'Panna Daj Spokój',
  'Piekielna Landryna',
  'Ostatni Shot',
  'Dzika po Północy',
  'Madame Przegięcie',
  'Księżna Rozróby',
  'Wódczana Wróżka',
  'Pani Trzymaj Mnie',
  'Słodka Katastrofa',
  'Złota Łajza',
  'Króliczka Kłopotów',
  'Barbie po Burzy',
  'Panna Ostra Riposta',
  'Neonowa Bestia',
  'Dama z Pazurem',
  'Kacowa Cesarzowa',
  'Pani Żadnych Dowodów',
  'Laska od Afer',
  'Tańcząca Pokusa',
  'Pani Znikam nad Ranem',
  'Szeryfka Grzechu',
  'Kowbojka Nie Do Opanowania',
  'Niebezpieczna Migotka',
  'Królowa Sprośnych Żartów',
  'Panna Jeszcze Jednego',
  'Ostra Jak Tabasco',
  'Błyszcząca Rozpusta',
  'Nocna Diablica',
  'Pani Bez Wstydu',
  'Rozbójniczka w Szpilkach',
  'Saloonowa Petarda',
  'Pijana Iskra',
  'Księżniczka Kaca',
  'Wulgarna Wróżka',
  'Panna Cholera Jasna',
  'Kurwa Mać Kowbojka',
  'Dama od Grubych Akcji',
  'Grzeszna Druhna',
  'Ta z Zakazanej Loży',
  'Pani Robimy Dym',
  'Kacowa Królowa',
  'Panna Gruby Przypał',
  'Szalona Szeptucha',
  'Ognista Kokarda',
  'Diablica z Parkietu',
  'Pani Ostatnia Kolejka',
  'Kieliszkowa Wiedźma',
  'Słodka Bezczelna',
  'Królowa Brudnych Sekretów',
  'Panna Będzie Wstyd',
  'Roztańczona Bomba',
  'Ta od Niegrzecznych Planów',
  'Piekielny Brokat',
  'Laleczka z Problemami',
  'Szpilkowa Wariatka',
  'Pani Jeszcze Nie Koniec',
  'Kowbojka po Przejściach',
  'Sprośna Róża',
  'Wódczana Dama',
  'Ta od Szybkich Shotów',
  'Gorąca Awantura',
  'Panna Zrobię Scenę',
  'Królowa Plot Twistów',
  'Niegrzeczna Migotka',
  'Pani Zły Pomysł',
  'Saloonowa Grzesznica',
  'Kac Vegas',
  'Słodka Psychoza',
  'Błyszcząca Bezbożnica',
  'Panna Nie Pytaj',
  'Ruda Demolka',
  'Cukierek z Piekła',
  'Seksowna Katastrofa',
  'Pani Gorący Bałagan',
  'Koktajlowa Bestia',
  'Dziewczyna od Dymów',
  'Ta z Nieczystym Sumieniem',
  'Królowa Głupich Decyzji',
  'Pijacka Perełka',
  'Panna Zakazany Owoc',
  'Wredna Kusicielka',
  'Ostra Bomboniera',
  'Neonowa Rozrabiaka',
  'Pani Rozpinam Noc',
  'Dama z Promilami',
  'Sprośna Gwiazdeczka',
  'Laska Bez Instrukcji',
  'Piekielna Szpilka',
  'Ta od Aftera',
  'Barmanka Grzechu',
  'Rozkoszna Afera',
  'Księżniczka Przypału',
  'Panna Całuj i Uciekaj',
  'Kieliszek Pokusy',
  'Czarownica od Shotów',
  'Ostra Jak Żyleta',
  'Pani Niegrzeczny Uśmiech',
  'Kowbojka na Gigancie',
  'Dzika Bez Smyczy',
  'Słodka Bez Litości',
  'Ta od Brudnych Tańców',
  'Panna Nie Ma Hamulców',
  'Grzeszny Brokat',
  'Zadziorna Rakieta',
  'Pani Co Ja Robię',
  'Barowa Diablica',
  'Szampanowa Wariatka',
  'Panna Rozpierdol',
  'Kacowa Diva',
  'Ta od Nocnych Akcji',
  'Pikantna Szeryfowa',
  'Rozpalona Blondyna',
  'Pani Nie Patrz na Mnie',
  'Wódka z Brokatem',
  'Sprośna Petarda',
  'Lalunia od Skandali',
  'Księżna Pożądania',
  'Panna Mam Plan',
  'Niegrzeczna Rakieta',
  'Dziewczyna od Złych Pomysłów',
  'Pani Tylko Jeden Drink',
  'Ognista Żmijka',
  'Saloonowa Suka',
  'Ta od Gorących Plotek',
  'Panna Bez Cenzury',
  'Kokietka z Piekiełka',
  'Pani Kurwa No Nie',
  'Błyszcząca Drapieżnica',
  'Nocna Pokusa',
  'Druhna Demolka',
  'Królowa Chaosu',
  'Panna Wstyd Jutro',
  'Niebezpieczna Landryna',
]
