export const FUNNY_NAMES = [
  'Dzika Landryna',
  'Szeryfowa Aneta',
  'Różowa Pantera',
  'Kowbojka Kasia',
  'Pijana Pszczółka',
  'Gwiazda Szeryfa',
  'Neonowa Klacz',
  'Złota Ostroga',
  'Buntowniczka',
  'Saloonowa Królowa',
  'Whiskey Lady',
  'Galopująca Gazela',
  'Szalona Ruda',
  'Ostra Tequila',
  'Złota Gwiazda',
  'Różowy Dynamit',
  'Galopująca Panna',
  'Królowa Parkietu',
  'Wieczorowa Dama',
  'Błyszcząca Ostroga',
  'Neonowa Amazonka',
  'Gorąca Czekolada',
  'Słodka Zemsta',
  'Karmazynowa Dama',
  'Diamentowa Przełęcz',
  'Srebrna Podkowa',
  'Błękitna Laguna',
  'Śpiewająca Syrena',
  'Tańcząca z Wilkami',
  'Wielka Błękitna',
  'Słońce Teksasu',
  'Dzika Orchidea',
  'Perłowa Dama',
  'Rubinowa Róża',
  'Szmaragdowa Dolina',
]
